### ISSUE TITLE
1.0 rc7 [frontpage] not working

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#98] opened 2019-04-11 23:53 UTC
Just following the instructions to specify different graphs for the [frontpage] and [today] sections but [frontpage] is not registering - the skin continues to use [today]

Frontpage should have windrose but not battery graph, Today should have battery graph and no windrose

**_Add highcharts_frontpage_graphgroup = frontpage to the [[Belchertown]] [[[Extras]]] stanza in the weewx.conf file. You then add a new Chart Group section in graphs.conf called [frontpage]. Under this section add the graphs you want plotted on the frontpage with their associated options._**

Added the [frontpage] stanza in the graphs.conf
Restarted weewx

I've also tried highcharts_frontpage_graphgroup = "frontpage" with no change.

There are no errors that I can see watching the syslog

[[Belchertown]]
        HTML_ROOT = /var/www/html/weewx/belchertown
        skin = Belchertown

        [[[Extras]]]

        # General Site Defaults
        belchertown_debug = 0
        belchertown_root_url = "http://41south.net.nz"
        theme = light
        theme_toggle_enabled = 1
        logo_image = "http://41south.net.nz/wellington.jpg"
        site_title = "41South NZ"
        radar_html = "<iframe width="650" height="360" src="https://embed.windy$
        footer_copyright_text = "41South.nz"
        footer_disclaimer_text = "Never make important decisions based on infor$
        highcharts_frontpage_graphgroup = frontpage

Graphs.conf snippet
[frontpage]
    time_length = today
    gapsize = 300000

        [[chart1]]
        title = Temperature
        [[[outTemp]]]
            zIndex = 1
            name = Temperature
        [[[dewpoint]]]
        [[[appTemp]]]
            color = "#f7a35c"

**Comment by biltmorelaker** [comment] 2019-04-12 00:01
It looks like your Graphs.conf snippet has a "`" (backtick) in front of the stanza [frontpage]. Is that correct or an artifact from copying. It should not be there.

**Comment by 41south** [comment] 2019-04-12 00:05
That's not there in the file - it's some sort of weird formatting when I posted it here using the 'code' button

**Comment by biltmorelaker** [comment] 2019-04-12 00:08
OK. It was a MarkDown artifact. Try a full reload of your frontpage with Alt-F5.

**Comment by 41south** [comment] 2019-04-12 00:13
Or Command-F5 on the Mac, but no difference there either. All other changes happen on the fly

**Comment by biltmorelaker** [comment] 2019-04-12 00:14
That's not it. I tried it, also. Did you restart weewx? You made a change in weew.conf. So you need to do that.

**Comment by 41south** [comment] 2019-04-12 00:19
Sure did, all the above, many times

**Comment by 41south** [comment] 2019-04-12 00:20
Have you had or got this working?

**Comment by biltmorelaker** [comment] 2019-04-12 00:22
I think we'll have to get @poblabs  to chime in. In the meantime, attach a copy of your graphs.conf file.

Yes it works fine for me [https:/wx.kutzenco.com](url). If you look at my frontpage, you'll see the time period is since midnight. On the Graphs/Today page it is the last 25 hours or so.

**Comment by 41south** [comment] 2019-04-12 00:26
Can't attach a conf file, copy paste it is :)
<snip>
# Global Chart Defaults
# These are fallback options that charts will use if an option is not defined. 
aggregate_type = None
time_length = 90000 # Last 25 hours
type = line
colors = "#268bd2, #90ed7d, #f7a35c, #d33682, #8085e9, #e4d354, #f15c80, #8085e8, #8d4653, #91e8e1"

[frontpage]
    time_length = today
    gapsize = 300000

	[[chart1]]
        title = Temperature
        [[[outTemp]]]
            zIndex = 1
            name = Temperature
        [[[dewpoint]]]
        [[[appTemp]]]
            color = "#f7a35c"

	[[chart2]]
        # The combined Wind Chart works best in this configuration
        title = Wind Speed and Direction
        yaxis_min = 0
        [[[windDir]]]
            zIndex = 1
            yAxis = 1
            yaxis_max = 360
            lineWidth = 0
            [[[[marker]]]]
                enabled = true
            [[[[states]]]]
                [[[[[hover]]]]]
                        lineWidthPlus = 0
        [[[windGust]]]
        [[[windSpeed]]]
            zIndex = 2

	[[chart3]]
        title = Rain
        [[[rainRate]]]
            yAxis = 1
        [[[rainTotal]]]
            name = Rain Total

	[[chart4]]
        title = Barometer
        type = spline
        [[[barometer]]]
            color = "#BECC00"

	[[chart5]]
        title = Solar Radiation and  UV Index
        [[[radiation]]]
           name = Solar Radiation
           zIndex = 1
           color = "#ffc83f"
        [[[maxSolarRad]]]
            type = area
            color = "#f7f2b4"
            y_label = "W/m2"
            name = Calculated Max Solar
        [[[UV]]]
            yAxis = 1
            yaxis_min = 0
            yaxis_max = 12
            color = "#90ed7d"
            y_label = "UV"
            name = UV Index
            zIndex = 2

	[[chart6]]
        title = Wind Rose
        [[[windRose]]]	


[day]
    # Chart Timespan Defaults
    time_length = today
    gapsize = 300000 # This should be your archive_interval from weewx.conf multiplied by 1000 to get milliseconds. Standard is 5 minutes

    [[chart1]]
        title = Temperature
        [[[outTemp]]]
            zIndex = 1
            name = Temperature
        [[[dewpoint]]]
	[[[appTemp]]]
            color = "#f7a35c"

	[[chart2]]
        # The combined Wind Chart works best in this configuration
        title = Wind Speed and Direction
        yaxis_min = 0
        [[[windDir]]]
            zIndex = 1
            yAxis = 1
            yaxis_max = 360
            lineWidth = 0
            [[[[marker]]]]
                enabled = true
            [[[[states]]]]
                [[[[[hover]]]]]
                        lineWidthPlus = 0
        [[[windGust]]]
        [[[windSpeed]]]
            zIndex = 2
    
    [[chart3]]
        title = Rain
        [[[rainRate]]]
            yAxis = 1
        [[[rainTotal]]]
            name = Rain Total
    
    [[chart4]]
        title = Barometer
        type = spline
        [[[barometer]]]
            color = "#BECC00"
            
    [[chart5]]
        title = Solar Radiation and  UV Index
	[[[radiation]]]
	   name = Solar Radiation
	   zIndex = 1
	   color = "#ffc83f"
        [[[maxSolarRad]]]
	    type = area
	    color = "#f7f2b4"
            y_label = "W/m2"
            name = Calculated Max Solar
	[[[UV]]]
	    yAxis = 1
	    yaxis_min = 0
	    yaxis_max = 12
	    color = "#90ed7d"
	    y_label = "UV"
	    name = UV Index
	    zIndex = 2


     [[chart6]]
	  title = Battery
	  [[[consBatteryVoltage]]]
	  name = Tx Battery Voltage

[week]
    # Chart Timespan Defaults
    aggregate_type = max
    aggregate_interval = 3600 # 1 hour
    time_length = 604800 # Last 7 days
    gapsize = 3600000 # 1 hour in milliseconds

    [[chart1]]
        title = Temperature
        [[[outTemp]]]
            zIndex = 1
            name = Temperature
        [[[dewpoint]]]
        [[[appTemp]]]
            color = "#f7a35c"
    
    [[chart2]]
        # The combined Wind Chart works best in this configuration
        title = Wind Speed and Direction
        yaxis_min = 0
        [[[windDir]]]
            zIndex = 1
            yAxis = 1
            yaxis_max = 360
            lineWidth = 0
            # Here we can override the timespan default aggregate type with our own specific to this chart
            aggregate_type = avg
            [[[[marker]]]]
                enabled = true
            [[[[states]]]]
                [[[[[hover]]]]]
                        lineWidthPlus = 0
        [[[windGust]]]
        [[[windSpeed]]]
            zIndex = 2
    
    [[chart3]]
        title = Rain
        [[[rainRate]]]
            yAxis = 1
        [[[rainTotal]]]
            name = Rain Total
    
    [[chart4]]
        title = Barometer
        [[[barometer]]]
            color = "#BECC00"

        
[month]
    # Chart Timespan Defaults
    type = spline
    aggregate_type = max
    aggregate_interval = 86400 # 1 day
    time_length = 2592000 # Last 30 days
    gapsize = 86400000 # 1 day in milliseconds

    [[chart1]]
        title = Temperature
        [[[outTemp]]]
            zIndex = 1
            name = Max Temperature
            color = red
        [[[outTemp_min]]]
            name = Min Temperature
            observation_type = outTemp
            aggregate_type = min
            color = "#7cb5ec"
    
    [[chart2]]
        # The combined Wind Chart works best in this configuration
        title = Wind Speed and Direction
        yaxis_min = 0
        [[[windDir]]]
            zIndex = 1
            yAxis = 1
            yaxis_max = 360
            lineWidth = 0
            # Here we can override the timespan default aggregate type with our own specific to this chart
            aggregate_type = avg
            [[[[marker]]]]
                enabled = true
            [[[[states]]]]
                [[[[[hover]]]]]
                        lineWidthPlus = 0
        [[[windGust]]]
        [[[windSpeed]]]
            zIndex = 2
    
    [[chart3]]
        title = Rain
        type = line
        [[[rainRate]]]
            yAxis = 1
        [[[rainTotal]]]
            name = Rain Total
    
    [[chart4]]
        title = Barometer
        [[[barometer]]]
            color = "#BECC00"
        
[year]
    # Chart Timespan Defaults
    type = spline
    aggregate_type = max
    aggregate_interval = 86400 # 1 day
    time_length = year
    gapsize = 86400000 # 1 day in milliseconds

    [[chart1]]
        title = Temperature
        [[[outTemp]]]
            zIndex = 1
            name = Max Temperature
            color = red
        [[[outTemp_min]]]
            name = Min Temperature
            observation_type = outTemp
            aggregate_type = min
            color = "#7cb5ec"
    
    [[chart2]]
        # The combined Wind Chart works best in this configuration
        title = Wind Speed and Direction
        yaxis_min = 0
        [[[windDir]]]
            zIndex = 1
            yAxis = 1
            yaxis_max = 360
            lineWidth = 0
            # Here we can override the timespan default aggregate type with our own specific to this chart
            aggregate_type = avg
            [[[[marker]]]]
                enabled = true
            [[[[states]]]]
                [[[[[hover]]]]]
                        lineWidthPlus = 0
        [[[windGust]]]
        [[[windSpeed]]]
            zIndex = 2
    
    [[chart3]]
        title = Rain
        type = line
        [[[rainRate]]]
            yAxis = 1
        [[[rainTotal]]]
            name = Rain Total
    
    [[chart4]]
        title = Barometer
        [[[barometer]]]
            color = "#BECC00"

**Comment by biltmorelaker** [comment] 2019-04-12 00:32
Ugh. Maybe zip it up or tar it and attach it?

**Comment by 41south** [comment] 2019-04-12 02:18
[graphs.txt](https://github.com/poblabs/weewx-belchertown/files/3071293/graphs.txt)
Changed it graphs.txt, just rename to graphs.conf

**Comment by 41south** [comment] 2019-04-12 03:11
Just by way of a test I swapped the two stanzas around, renamed [frontpage] to [day] and [day] to [frontpage]. The [day] loaded fine and the windrose came up so there is no issue with the stanza syntax, it's purely that [frontpage] is not being picked up

**Comment by 41south** [comment] 2019-04-12 03:27
Ok - problem solved. This instruction is not really correct **"To do this, first add highcharts_frontpage_graphgroup = frontpage to the [[Belchertown]] [[[Extras]]] stanza in the weewx.conf file."** This already exists in the weewx.conf/skin.conf (if you did like I did and copied over all the new Extras to weewx.conf) so by adding it again I created two of them. The first pointed to [frontpage] but then the second pointed back to [day] - so day it was!

Now I have just one entry it works fine:) I'll leave this open to you guys have read it, but perhaps just clarify that instruction.

@biltmorelaker thanks for your help, I had to go back and re-read quite a bit to realise what the issue was

**Comment by biltmorelaker** [comment] 2019-04-12 12:39
Great that you got it working!!

Here's my philosophy on skins.conf and weewx.conf. The skins.conf Extras section contains all of the variables that a user (implementer of a skin) can set and that they are set to default values. Some people advocate making changes directly in skin.conf to change those values. Any of those variables can also be put into the [[[Extras]]] stanza of weewx.conf for the skin. Any values set in weewx.conf override the values in skin.conf. One of the advantages of defining an Extra value in weewx.conf rather than changing it in skin.conf is that it will survive an upgrade to the skin (which generally ends up replacing skin.conf).

I always felt that you should only add an Extras value to weewx.conf if you want to change it from the default value which was set in skin.conf or if it is required (like belchertown_root_url for the skin to work).  It makes it easier (and perhaps less confusing) for users,  not to instruct them to copy all the Extras variables over. It also keeps from loading up weewx.conf with entries that aren't needed, making it easier to read. In addition, if the author changes a skin.conf default to adjust the skin in some way when he or she issues an upgrade, weewx.conf doesn't impact that change when you apply the upgrade.

You are more sophisticated than many and it seems you copied all of the Extras from skin.conf into weewx.conf. So following the instruction in the wiki to add a value resulted in your adding something you had already added. 

Regarding graphs on the frontpage, @poblabs set things up so that graphs there would be the same as those defined in the [day] stanza of graphs.conf. He was not a fan of making a fixed separate stanza for the frontpage (I personally think it would be a popular option). Instead he set up an Extras value that would allow the user to define a new stanza for the frontpage. I think you could actually use that Extras variable to specify the stanza name to be anything you want (though I haven't tried it) as long as you are consistent in graphs.conf. Using [frontpage] just seems to make sense.

So. the feeling was that setting up a special stanza for the frontpage would be an advanced option. The wiki page was written with that in mind and the expectation that users wouldn't start by copying a default version from skins.conf into weewx.conf.

Let me see about updating the wiki page description to account for users like you that copy all of the Extras into weewx.conf. I'll also check with @poblabs  to see what he wants.

Sorry for the long story here. Again - Glad you got it working!!

**Comment by biltmorelaker** [comment] 2019-04-12 12:58
OK. I updated the wiki page - at least preliminarily. We'll see if @poblabs wants to edit that. Given the change, I'll close this Issue.

**Comment by biltmorelaker** [comment] 2019-04-12 12:59
Wiki page updated.

**Closed by biltmorelaker** 2019-04-12 12:58 UTC

**Comment by poblabs** [comment] 2019-04-12 18:45
Hey guys, glad you've got this sorted. I have a head cold so have been under the weather and haven't had the energy to do much other than watch TV 😃 Some quick comments based on @biltmorelaker's reply. 

> I think you could actually use that Extras variable to specify the stanza name to be anything you want

Correct! If you're like me and have a chart on the about page, you could make `highcharts_frontpage_graphgroup = about` and it'll show the `[about]` graph group from graphs.conf. 

> He was not a fan of making a fixed separate stanza for the frontpage (I personally think it would be a popular option).

Well given how it's both of you using it, and I think there's only 3 or 4 people using the dev skin, maybe it is a popular feature. Maybe I should rethink this and make `[frontpage]` a permanent fixture (even if it does mirror `[day]` when it ships with default graphs)..?

**Comment by biltmorelaker** [comment] 2019-04-12 21:39
@poblabs, Get some rest and hope you feel better soon!

I do think you should make `[frontpage]` a permanent fixture (mirroring `[day]` as a default in the **graphs.conf.example** file). In the end it's less confusing to a user than requiring enabling it with an `[[[Extras]]]` variable.

But it can certainly wait until you finish your TV 📺 binging.

**Comment by captain-coredump** [comment] 2019-04-12 21:44
My vote is to have a separate [frontpage] out of the box.  I personally
want the last 25 hours displayed on the front page, and calendar day is
fine for the day reports page...

-- 
Sent from my iEtch-a-Sketch via subspace

**Comment by poblabs** [comment] 2019-04-12 21:47
@biltmorelaker @captain-coredump @41south Ok, works for me. Now for semantics because I love to overthink things;

Should it be `[frontpage]` or `[home]` (which matches the Navigation) or `[homepage]`?

**Comment by 41south** [comment] 2019-04-12 22:19
I danced around this one yesterday while I was trying to get it working,
but ended up coming back to [FrontPage]. However I think that [homepage] is
possibly more of a well known term for website entry, and matches Home in
the menu, so that would be my vote.

**Comment by 41south** [comment] 2019-04-12 22:55
@biltmorelaker @poblabs just to add my philosophy on the whole skin.conf/weewx.conf thing - I think we think alike pretty much. At the start I left everything for weewx in that conf and everything for the skin in that conf, but as the changes started to come and I was testing a lot it became pretty clear that updating skin.conf all the time was labor intensive (to say the least!). With this upgrade I looked at skin.conf and just pulled everything I thought would be used to configure and customise the skin and put it into [[[extras]]] in weewx.conf. That's where I fell over because at the time I copied stuff without fully understanding why it was there. I imagine some others may do the same .....maybe :) I've been trying to follow the Wiki write-ups from the "dummy" point of view to see what might trip other users up. I'm not new to IT by any means - I started out when DOS 1.0 was on 51/4 floppy disks and Z80 procs were new and exciting. That was 40 some years ago now and I'm still up to my armpits in it pretty much every day - my how time flies. Anyway I digress!! I'm sure I possibly over-think a bit more than the average user and reading the manual isn't always a strength. Each time I read the Wiki on the graphs I pick up on something else, so it's a great reference and well done @ on that. @poblabs Pat you have done an awesome job on this skin, it's the best there is hands down, especially now with the new graphs stuff. Hopefully I can contribute in some small way to iron out any wrinkles. Cheers guys.

**Comment by biltmorelaker** [comment] 2019-04-12 23:08
@poblabs @41south I second Colin's vote on calling the stanza [homepage].

**Comment by poblabs** [comment] 2019-04-12 23:21
@41south Thanks! Appreciate that!

@biltmorelaker Cool. `[homepage]` it is. 

I'll work on making that permanent later. I'll update `graphs.conf.example` with a copy of `[day]` for `[homepage]` and update the `highcharts_homepage_graphgroup` option to `highcharts_homepage_graphgroup = homepage`

**Comment by captain-coredump** [comment] 2019-04-13 01:25
Can you make the default [homepage] graphs show the previous 25 hours, and the [day] graphs show the calendar day?  It is nice to be able to look at trends when walking by the tablet at 1:00 AM on your way to the weather observer's lounge, and the homepage graphs are pretty thin at those wee hours of the morning.  Yes, I can edit my own, but it seems like a better default for everyone especially with a dedicated [homepage] section...

-- 
Sent from my iEtch-a-Sketch via subspace

**Comment by biltmorelaker** [comment] 2019-04-13 02:30
@captain-coredump Wait - you're up at 1:00AM heading to the weather observer's lounge 😉? I'm impressed, I think I remember when I was able to stay up that late, but it was long, long ago 😏.

 It may make sense to have both [homepage] and [day] default to "since midnight" (`time_length=today`) as that is the way V0.9x is set. So, changing that default may confuse some people. 

As you point out, thanks to the changes @poblabs made for V1, you can easily make the changes yourself by editing the new graphs.conf file to do that. See the wiki page syntax section (https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation#syntax) for instructions on making changes like that.

In graphs.conf you just change the **Chart Level Group Options** for [homepage] by entering `time_length = 90000 ` which will yield plots for the last 25 hours. And change the **Chart Level Group Options** for [day] by entering `time_length=today` which will yield plots since midnight. 

Once you do that, the changes will be retained across future upgrades.

It's @poblabs' decision, of course.

**Comment by captain-coredump** [comment] 2019-04-13 15:27
Wait until you get to be my age, and have to TiVo the 6 o'clock news because you can't stay awake! :-)  The only thing keeping me alive right now is massive doses of diuretics (that nurses jokingly call vitamin pee), and that means hourly trips to the weather observer's lounge day and night.

Anyway, my thought for using different time_length between the [homepage] and [day] is to make a reason for having the two different config blocks in the first place.  Look at the home page at 1:00 AM and it will make sense, and doing the last 25'ish hours is what WeeWX's own Standard skin did for years probably for this very reason.

I just had to deal with another shortfall of time_length=today this morning, while troubleshooting a packet-loss issue at someone else's site running my WeeWX WeatherFlow UDP station driver.  The site owner sent me a link to their 0.91 Belchertown skin, claiming frequent gaps in the data.  When I looked at their station link, it was 3:00 AM station time and there wasn't much data to look at.  The gaps were too small to be caught in the weekly graph, so I basically have to wait until well after my bed time tonight to see a full day's data without having them re-config their skin.  (The problem is definitely with the station driver missing LOOP packets.)

Yes, I have already put my fingerprints all over the v1.0 graphs.conf for my own customizations, to fix my personal dislike for [day] graphs at 1:00 AM without a [yesterday] option to figure out what happened two hours ago.  Hence, my suggestion to take advantage of the v1.0 rollout and [homepage] versus [day] split to implement a last 25 graph on the front page as the default to mimic what WeeWX's Standard skin already does...

-- 
Sent from my iEtch-a-Sketch via subspace
