### ISSUE TITLE
Refresh hooks when MQTT enabled

### ISSUE THREAD

**Issue by trdischat** [poblabs/weewx-belchertown#370] opened 2020-08-26 05:14 UTC
I send data from weewx running on a pi on my home network to a mosquitto MQTT broker running on a DO droplet.  The pi also generates the web pages using the Belchertown skin and uploads the site to the droplet using rsync so that I can access the site anywhere.  MQTT websockets are enabled in the Belchertown skin.  The site updates live as promised.  But if MQTT is enabled, then my custom content that is inserted into the home page using `index_hook_after_station_info.inc` and `index_hook_after_charts.inc` never updates.  If I disable MQTT websockets in Belchertown, the whole page updates every five minutes, including the hook inserts.  Any way to use MQTT and enable autorefresh on the hooked content?

**Comment by trdischat** [comment] 2020-08-27 06:22
I dug around in the closed issues for a while and I think I partially answered my own question.  I read that the hooks will update **images** but not text in the custom inserts.  So any weather data variables that I add to a custom section will not update if I use MQTT.  I was hoping to create a custom colored display of the Air Quality Index using the weewx-purpleair and weewx-aqi extensions.  But it looks like this is not possible without hacking the actual Belchertown template files, since the custom inserts don't update if you have enabled MQTT.  Do I have that right?

**Comment by Brezentrager** [comment] 2020-08-27 09:07
Hi trdischat,
I ran into the same issue on my site. My plan was to display the current sunshine hours in one of the hooks.
When discussing the plan with Pat he confirmed that currently only images get updated automatically (as you already found out). 

I have now implemented a custom functionality for my site. In a nutshell:

- In every reporting cycle I create a html-site that's copied to my web server
- On the main main page of my site I've included a small script with a timer (currently set to 10 seconds)
- Every time the timer fires, the content of the hook gets updated with the content of the html file (of step 1)

In case you are interested, I can send you more information.

**Comment by ArendPWS** [comment] 2020-08-27 10:51
My (open) pull request is about this issue.

[Add optional label to main sensor](https://github.com/poblabs/weewx-belchertown/pull/357)

This pull request is about creating a "clean" row/div beneath the observation row wich can be used to insert user code. The code used to support my additional thermo/hygro sensor is in its own .inc file. All needed js, css and html is combined into one file. MQTT is supported in this .inc file by means of replacing/extending the existing js functions like this:

Small part of the javascript in user_extension.inc:

	
	var old_update_weewx_data = update_weewx_data;
	update_weewx_data = function(data) {
		old_update_weewx_data.apply(this, arguments);

               **Your code goes here.**

	};

	
	var old_update_current_wx = update_current_wx;
	update_current_wx = function(data) {
		old_update_current_wx.apply(this, arguments);

               **Your code goes here.**

	};

**Comment by poblabs** [comment] 2020-08-27 13:27
You're right, the `.inc` files will only update the images within. This is because the files are created on weewx's archive interval, then they are merged into the final HTML file that is served on the website. You could give @Brezentrager solution a try, that might work well for refreshing the content using an iframe or something.

**Comment by poblabs** [comment] 2020-08-27 13:27
@ArendPWS I'm going to check your pull request in more detail today I hope!

**Comment by poblabs** [comment] 2020-09-08 19:20
Closing this based on my comments earlier.

**Closed by poblabs** 2020-09-08 19:20 UTC
