### ISSUE TITLE
Translate Alert_ effect DarkSky 

### ISSUE THREAD

**Issue by Bug-Storm** [poblabs/weewx-belchertown#347] opened 2020-07-29 15:45 UTC
Hello Guys , it's problem translate Alert _effect of DarkSky ? Thanks 

![chrome_8IaFAnrAR4](https://user-images.githubusercontent.com/68688876/88821661-3cf8fd00-d1c3-11ea-8fd7-f95b7fa5922e.png)

**Comment by poblabs** [comment] 2020-08-09 00:11
Duplicate of #352, closing. See updates there

**Closed by poblabs** 2020-08-09 00:11 UTC
