### ISSUE TITLE
Areaspline Graph Marker & Radius

### ISSUE THREAD

**Issue by HoracioDos** [poblabs/weewx-belchertown#160] opened 2019-06-06 22:11 UTC
Hello Pat:
I want to disable areaspline marker (small purple squares) but it doesn't work. What am I doing wrong? Also If I set radius = 5 for winDir, it is very nice until I hover it. Then a big marker appears. I tried to use the same radius value on hover but it doesn't work too.
Thanks!

```
    [[chart4]]
        # The combined Wind Chart works best in this configuration
        title = Dirección y Velocidad del Viento
        yaxis_min = 0
        [[[windDir]]]
            zIndex = 1
            yAxis = 1
            yaxis_max = 360
            lineWidth = 0
            # Here we can override the timespan default aggregate type with our own specific to this chart
            aggregate_type = avg
            color = "#D33681"
            [[[[marker]]]]
                enabled = true
                # radius = 2
            [[[[states]]]]
                [[[[[hover]]]]]
                        lineWidthPlus = 0
        [[[windGust]]]
            color = "#90ed7d"
            aggregate_type = max
        [[[windSpeed]]]
            type = areaspline
            color = "#8085e9"
            aggregate_type = max
            [[[[marker]]]]
                enabled = false
```

![image](https://user-images.githubusercontent.com/4549674/59069510-ba5e0180-888d-11e9-8cce-7fa664f9cec4.png)

**Comment by poblabs** [comment] 2019-06-06 22:25
1. radius on hover. I do not know why it does this. Nowhere in the code do I specify hover size. 

2. areaspline remove the marker: I don't know why it's not removing it. I can see in the json code that it's defined, but the chart isn't picking it up. I will need to research this one. 

```
      "windSpeed": {
        "name": "Wind Speed",
        "color": "#8085e9",
        "data": [
          [
            1559258400000,
            1.17
          ],
          [
            1559262000000,
            0.25
          ],
          [
            1559265600000,
            0.39
          ],
          [
            1559269200000,
            0.39
          ],
          [
            1559272800000,
            0.17
          ],
          [
            1559276400000,
            0.69
          ],
          [
            1559280000000,
            0.57
          ],
          [
            1559283600000,
            0.36
          ],
          [
            1559287200000,
            1.37
          ],
          [
            1559290800000,
            0.78
          ],
          [
            1559294400000,
            0.43
          ],
          [
            1559298000000,
            0
          ],
          [
            1559301600000,
            0
          ],
          [
            1559305200000,
            0.63
          ],
          [
            1559308800000,
            1.45
          ],
          [
            1559312400000,
            3.55
          ],
          [
            1559316000000,
            4.16
          ],
          [
            1559319600000,
            4.31
          ],
          [
            1559323200000,
            5
          ],
          [
            1559326800000,
            3.94
          ],
          [
            1559330400000,
            5.49
          ],
          [
            1559334000000,
            4.48
          ],
          [
            1559337600000,
            5.26
          ],
          [
            1559341200000,
            3.44
          ],
          [
            1559344800000,
            1.72
          ],
          [
            1559348400000,
            0
          ],
          [
            1559352000000,
            0
          ],
          [
            1559355600000,
            0
          ],
          [
            1559359200000,
            0.75
          ],
          [
            1559362800000,
            0
          ],
          [
            1559366400000,
            0
          ],
          [
            1559370000000,
            0
          ],
          [
            1559373600000,
            0
          ],
          [
            1559377200000,
            0
          ],
          [
            1559380800000,
            0
          ],
          [
            1559384400000,
            0
          ],
          [
            1559388000000,
            1.29
          ],
          [
            1559391600000,
            1.3
          ],
          [
            1559395200000,
            2.1
          ],
          [
            1559398800000,
            2.01
          ],
          [
            1559402400000,
            2.63
          ],
          [
            1559406000000,
            2.41
          ],
          [
            1559409600000,
            2.03
          ],
          [
            1559413200000,
            2.03
          ],
          [
            1559416800000,
            1.24
          ],
          [
            1559420400000,
            1.6
          ],
          [
            1559424000000,
            0.94
          ],
          [
            1559427600000,
            1.12
          ],
          [
            1559431200000,
            0.01
          ],
          [
            1559434800000,
            0.09
          ],
          [
            1559438400000,
            0.04
          ],
          [
            1559442000000,
            0.01
          ],
          [
            1559445600000,
            0
          ],
          [
            1559449200000,
            0
          ],
          [
            1559452800000,
            0
          ],
          [
            1559456400000,
            0
          ],
          [
            1559460000000,
            0
          ],
          [
            1559463600000,
            0
          ],
          [
            1559467200000,
            0
          ],
          [
            1559470800000,
            0.36
          ],
          [
            1559474400000,
            0
          ],
          [
            1559478000000,
            1.2
          ],
          [
            1559481600000,
            1.06
          ],
          [
            1559485200000,
            1.45
          ],
          [
            1559488800000,
            2.15
          ],
          [
            1559492400000,
            2.74
          ],
          [
            1559496000000,
            2.66
          ],
          [
            1559499600000,
            2.5
          ],
          [
            1559503200000,
            2.15
          ],
          [
            1559506800000,
            1.96
          ],
          [
            1559510400000,
            2.31
          ],
          [
            1559514000000,
            2.13
          ],
          [
            1559517600000,
            1.54
          ],
          [
            1559521200000,
            0.79
          ],
          [
            1559524800000,
            5.67
          ],
          [
            1559528400000,
            3.72
          ],
          [
            1559532000000,
            0.81
          ],
          [
            1559535600000,
            0.78
          ],
          [
            1559539200000,
            0.87
          ],
          [
            1559542800000,
            0
          ],
          [
            1559546400000,
            0.14
          ],
          [
            1559550000000,
            0
          ],
          [
            1559553600000,
            0
          ],
          [
            1559557200000,
            0
          ],
          [
            1559560800000,
            0.76
          ],
          [
            1559564400000,
            3.36
          ],
          [
            1559568000000,
            1.62
          ],
          [
            1559571600000,
            5.05
          ],
          [
            1559575200000,
            6.45
          ],
          [
            1559578800000,
            4.65
          ],
          [
            1559582400000,
            5.8
          ],
          [
            1559586000000,
            7.8
          ],
          [
            1559589600000,
            5.58
          ],
          [
            1559593200000,
            7.46
          ],
          [
            1559596800000,
            5.88
          ],
          [
            1559600400000,
            8.12
          ],
          [
            1559604000000,
            8.38
          ],
          [
            1559607600000,
            4.35
          ],
          [
            1559611200000,
            3.6
          ],
          [
            1559614800000,
            0
          ],
          [
            1559618400000,
            0
          ],
          [
            1559622000000,
            0
          ],
          [
            1559625600000,
            0
          ],
          [
            1559629200000,
            0
          ],
          [
            1559632800000,
            0
          ],
          [
            1559636400000,
            0
          ],
          [
            1559640000000,
            0
          ],
          [
            1559643600000,
            0.82
          ],
          [
            1559647200000,
            0.6
          ],
          [
            1559650800000,
            3.98
          ],
          [
            1559654400000,
            2.74
          ],
          [
            1559658000000,
            3.07
          ],
          [
            1559661600000,
            4.54
          ],
          [
            1559665200000,
            3.55
          ],
          [
            1559668800000,
            4.98
          ],
          [
            1559672400000,
            5.48
          ],
          [
            1559676000000,
            6.71
          ],
          [
            1559679600000,
            4.11
          ],
          [
            1559683200000,
            3.4
          ],
          [
            1559686800000,
            2.44
          ],
          [
            1559690400000,
            5.08
          ],
          [
            1559694000000,
            3.28
          ],
          [
            1559697600000,
            0.96
          ],
          [
            1559701200000,
            0
          ],
          [
            1559704800000,
            0
          ],
          [
            1559708400000,
            0
          ],
          [
            1559712000000,
            0
          ],
          [
            1559715600000,
            0.61
          ],
          [
            1559719200000,
            1.59
          ],
          [
            1559722800000,
            1.31
          ],
          [
            1559726400000,
            0.91
          ],
          [
            1559730000000,
            0.89
          ],
          [
            1559733600000,
            0.8
          ],
          [
            1559737200000,
            1.69
          ],
          [
            1559740800000,
            2.1
          ],
          [
            1559744400000,
            2.93
          ],
          [
            1559748000000,
            2.47
          ],
          [
            1559751600000,
            2.67
          ],
          [
            1559755200000,
            2.52
          ],
          [
            1559758800000,
            2.84
          ],
          [
            1559762400000,
            2.21
          ],
          [
            1559766000000,
            2.07
          ],
          [
            1559769600000,
            1.94
          ],
          [
            1559773200000,
            1.62
          ],
          [
            1559776800000,
            1.06
          ],
          [
            1559780400000,
            0.17
          ],
          [
            1559784000000,
            0.04
          ],
          [
            1559787600000,
            0.08
          ],
          [
            1559791200000,
            0.72
          ],
          [
            1559794800000,
            1.23
          ],
          [
            1559798400000,
            1.27
          ],
          [
            1559802000000,
            1.51
          ],
          [
            1559805600000,
            1.74
          ],
          [
            1559809200000,
            1.22
          ],
          [
            1559812800000,
            1.33
          ],
          [
            1559816400000,
            0.86
          ],
          [
            1559820000000,
            0.82
          ],
          [
            1559823600000,
            0.89
          ],
          [
            1559827200000,
            4.2
          ],
          [
            1559830800000,
            4.39
          ],
          [
            1559834400000,
            5.67
          ],
          [
            1559838000000,
            3.34
          ],
          [
            1559841600000,
            3.8
          ],
          [
            1559845200000,
            2.97
          ],
          [
            1559848800000,
            2.96
          ],
          [
            1559852400000,
            3.22
          ],
          [
            1559856000000,
            3.35
          ],
          [
            1559859600000,
            3.18
          ]
        ],
        "aggregate_type": "max",
        "yAxisLabel": "Wind Speed (mph)",
        "rounding": "1",
        "yaxis_min": "0",
        "marker": {
          "enabled": "false"
        },
        "obsType": "windSpeed",
        "type": "areaspline"
      }
```

**Comment by poblabs** [comment] 2019-06-07 12:17
Based on your issue #161, and the jsfiddle I created for that, I think I now know why the markers aren't working. It's a code issue on my side that I need to test with.

**Comment by poblabs** [comment] 2019-06-07 12:36
I take that back. I thought the marker was defined in the data of the series, but the marker is actually in the series where it should be. So I'm still unsure why it's not disabling like it should. 

![image](https://user-images.githubusercontent.com/3484775/59104325-4ceab900-88ff-11e9-96f1-04f0668e2d8e.png)

**Comment by poblabs** [comment] 2019-06-07 13:39
I think I see what is going on here. Same thing in #161 where the null was being parsed as a string "null", this false is being parsed as a string "false" and Highcharts wants it to be JavaScritpt's `false` - so it's being ignored. Need to determine a workaround.

**Comment by poblabs** [comment] 2019-06-07 14:18
Good news, the latest belchertown.py.tmpl has the new areaspline defaults with a disabled marker. So if you remove this line of code, it'll default to a disabled marker. 

```
            [[[[marker]]]]
                enabled = false
```

**Comment by HoracioDos** [comment] 2019-06-07 14:18
I'll try it right now!

**Comment by poblabs** [comment] 2019-06-07 14:20
The bad news is I still need to figure out the override and radius hover problem. I think it has to do with the string vs. integer problem that's going on.

**Comment by HoracioDos** [comment] 2019-06-07 14:29
I removed it from area and spline, I see that areaspline is not define in plotOptions. I don't know if some default is needed for it. Perhaps it should be defined like area.

**Comment by poblabs** [comment] 2019-06-07 14:32
Did you grab the latest belchertown.py.tmpl? It's in there as of https://github.com/poblabs/weewx-belchertown/commit/19ef03b2488eaea3d12f8de3ca18142d4cf00c46

https://github.com/poblabs/weewx-belchertown/blob/19ef03b2488eaea3d12f8de3ca18142d4cf00c46/skins/Belchertown/js/belchertown.js.tmpl#L997-L1007

**Comment by HoracioDos** [comment] 2019-06-07 14:34
No I didn't see that you have commited some changes. I'll sync upstream first.

**Comment by HoracioDos** [comment] 2019-06-07 15:51
All good
![image](https://user-images.githubusercontent.com/4549674/59116905-fabb8f00-8922-11e9-92a3-7a2c2041e333.png)

**Comment by poblabs** [comment] 2019-06-07 15:55
Sounds good. I think i also have a fix for the string/integer conversion problem. That was a tough one to chase. 

I will upload the belchertown.py here in this issue soon so you can test it.

**Comment by poblabs** [comment] 2019-06-07 17:56
@HoracioDos before I commit this, please try it out. 

Download: [belchertown.zip](https://github.com/poblabs/weewx-belchertown/files/3267055/belchertown.zip) and unzip and place it into your bin/user folder. 

1. Restart weewx and run wee_reports. Everything should look normal. Check all charts that everything is normal.
2. Now enable a marker on a chart with [[[[marker]]]] enabled = 1 and run wee_reports
3. Now disable a marker - like on the windDir - and those markers should go away. 
4. Re-enable the marker, and also enable hover, then enable marker hover radius size. Example:

```
            [[[[marker]]]]
                enabled = 1
                radius = 2
                [[[[[states]]]]]
                    [[[[[[hover]]]]]]
                        radius = 10
            [[[[states]]]]
                [[[[[hover]]]]]
                        enabled = true
                        lineWidthPlus = 0
```


In all my testing this method seems to be working with this new belchertown.py file.

**Comment by HoracioDos** [comment] 2019-06-07 18:13
Ok Thanks! I start with step 1. I'll keep you informed.!

**Comment by poblabs** [comment] 2019-06-07 18:19
@HoracioDos Try this updated version. Before I was only focused on series and markers. This updated version should look at everything. 

[belchertown.zip](https://github.com/poblabs/weewx-belchertown/files/3267146/belchertown.zip)

**Comment by poblabs** [comment] 2019-06-07 18:21
Here's what was going on. Every series on the chart (like windDir, outTemp, etc) has the option to have extra options applied to it, like the marker enable, and hover states. But Python was making the enable/disable option (the 1 or 0) a string (like "1" or "0"). JavaScript doesn't want it as a string, it wants it as an integer. 

So this update goes through every series and options underneath and converts anything that it can back to integer. Otherwise it leaves it as a string.

**Comment by HoracioDos** [comment] 2019-06-07 18:25
I'll replace belchertown.py again with the new one that you provided here. I'll let to know how it goes-

**Comment by poblabs** [comment] 2019-06-07 18:29
Great thanks! I may make even yet another change and apply this later down the process at the end of the data gathering. The end result should be the same as your testing though. So far everything looks good on my test system!

**Comment by HoracioDos** [comment] 2019-06-07 18:31
Don't worry I can test any new version as soon as you release it.

**Comment by HoracioDos** [comment] 2019-06-07 18:37
Step 1. Done. I didn't change any option in graphs.conf. Belchertown generator didn't show any error. All graphs are ok. Starting step 2 now.

**Comment by HoracioDos** [comment] 2019-06-07 19:25
All Done!

**Comment by poblabs** [comment] 2019-06-07 19:27
Great news!

On test 4, did you enable the hover like I did in my example? Or did it work for you automatically?

I had to enable = 1 in order to get the hover radius to work. 

``
            [[[[states]]]]
                [[[[[hover]]]]]
                        enabled = 1
```

**Comment by HoracioDos** [comment] 2019-06-07 19:34
No need to enable the hoover. It works as I pasted above.

**Comment by poblabs** [comment] 2019-06-07 19:37
Ok good! For me I have to enable it. I wonder why that is for me. This is good news, I think I'll commit it now. Big concern of mine is that nothing was broken once you installed it.

**Comment by poblabs** [comment] 2019-06-07 19:41
Oh I found out why. I have a section in the Highcharts config to disable hovering because the radius was so large. This update you tested fixes the large radius (string vs. integer values). So I can remove this section I think. 👍 

https://github.com/poblabs/weewx-belchertown/blob/master/skins/Belchertown/js/belchertown.js.tmpl#L1004-L1011

**Comment by HoracioDos** [comment] 2019-06-07 19:48
Excellent! I don't like any difference even if they work. They bounce in my head for days.
As fas as I can see, in` [[[[marker]]]] enable = true` doesn't break anything. All good then!

**Comment by poblabs** [comment] 2019-06-07 19:49
When changing a config below the observation (like [[[outTemp]]] or [[[barometer]]], etc.), anything like an `enable = true` won't work. We will always have to use 1 or 0. The "true" or "false" will get ignored and could cause unexpected behavior (like large radius on hover!)

I will commit those files later tonight. Thanks for testing!

**Comment by HoracioDos** [comment] 2019-06-07 19:54
> I will commit those files later tonight. Thanks for testing!

Don't mention it I'm glad to help you. I'll sync upstream as soon as you commit these changes.

**Comment by poblabs** [comment] 2019-06-07 23:51
Just committed the update. This one is a little different than the one you tested, but the end result should be the same. Please test it out again and let me know if you see anything weird! 

Hopefully 1.0.1 can go live this weekend

**Comment by HoracioDos** [comment] 2019-06-08 15:43
Hello Pat
I disabled and enabled markers again without any problems. I forgot to tell you that I didn't use wee_reports. I let belchertown generator run. Wee_reports doesn't cancel even if there are errors. I don't trust in it.

**Comment by poblabs** [comment] 2019-06-09 01:25
Thanks!

**Comment by poblabs** [comment] 2019-06-09 23:35
Closing since these updates went into 1.0.1

**Closed by poblabs** 2019-06-09 23:35 UTC

**Comment by HoracioDos** [comment] 2019-06-12 14:48
I set symbol keyword for marker a few minutes ago and it works as expected.
