### ISSUE TITLE
Indoor temperature

### ISSUE THREAD

**Issue by jhans1** [poblabs/weewx-belchertown#43] opened 2019-01-15 16:41 UTC
Indoor temperature is not displayed along with the outdoor temperature on the temperature graph (front page). How can this easily be displayed like with the weewx default skin/template?

**Comment by poblabs** [comment] 2019-01-15 17:52
Initially this was omitted since not everyone wants that. Now that there's the chart options I'll work on adding this as an option.

**Comment by poblabs** [comment] 2019-01-16 14:32
@jhans1 I've just pushed new commits for the indoor temp. Since I updated quite a bit your best bet may be to download the whole master branch. 

1. Go to the main page here, then on the right click `Clone or Download` then download the ZIP. 
2. Upload to your weewx and install with wee_extension just like you did previously.
3. Add the new option of `highcharts_show_intemp = 1` to your weewx.conf skin Extras. 
4. Restart weewx and wait for an archive interval. 

I followed the same plan that apparent temperature takes on the graphs where it's available on day and week charts only. 

My initial testing was successful for enable/disable (for security/safety reasons) and when enabled it shows on the day and week charts successfully. 

Please test it and close this issue when confirmed.

**Comment by poblabs** [comment] 2019-01-17 15:24
Closing this issue as I feel confident the options are there. It'll be released in 0.9 if you don't want to take the steps to upgrade to a beta version (as outlined in the previous reply).

**Closed by poblabs** 2019-01-17 15:24 UTC
