### ISSUE TITLE
Some ideas for future releases

### ISSUE THREAD

**Issue by HoracioDos** [poblabs/weewx-belchertown#119] opened 2019-05-08 21:35 UTC
I consider Belchertown almost complete at least for my needs. I would like to mention some ideas to make it perfect but at the same time I don't want to abuse of Pat's generosity.
- Add Heat and Cold waves in records page.
- Improve layout and style for tablets or other devices.
- Add new graphs capabilities.

Heat Waves
> The World Meteorological Organization (WMO) defines a heat wave as a period during which the daily maximum temperature exceeds for more than five consecutive days the maximum normal temperature by 9°F (5°C), the “normal” period being defined as 1961–1990.

This is our's weather service definition and how they calculate them.
> A heat wave is defined as a period in which the maximum and minimum temperatures equal or exceed, for at least 3 consecutive days and simultaneously, certain thresholds that depend on each location. These thresholds are based on Percentile 90 (P90), which can also be seen as the temperature above which someone is within the 10% of the highest temperatures for that place, according to the historical record of each location. Once this threshold is exceeded, a temperature is considered extreme.

Cold waves

I think that it might be quite important for people in the north hemisphere. I didn't find an exact definition for cold waves. As they aren't severe for us, our weather service didn't publish anything about them. Some instructions and directions are in this draft document "GUIDELINES ON THE DEFINTION AND MONITORING OF EXTREME WEATHER AND CLIMATE EVENTS" 
https://www.wmo.int/pages/prog/wcp/ccl/opace/opace2/documents/DraftversionoftheGuidelinesontheDefinitionandMonitoringofExtremeWeatherandClimateEvents.pdf

What do you think?

**Comment by poblabs** [comment] 2019-05-08 22:40
Some good suggestions. Seems like it would just be some database calculations over a period of time. 

Where would you suggest to show this data?

What other graph capabilities are you thinking of?

**Comment by HoracioDos** [comment] 2019-05-08 23:58
For heat and cold waves I imagined different methods. The easiest could be 3 arrays.
Waves_Months = Jan, Feb, March...
History_Max = value1, value2, value3
History_Min =  value1, value2, value3
For more complex ones, it would be necesary to create an external data base or load a textfile. Perhaps you can go back to the same month last year and take max and min temperature values from it to avoid loading external data
![HeatCold](https://user-images.githubusercontent.com/4549674/57415822-f4c37880-71d3-11e9-89f5-c1f258db5926.png)

**Comment by HoracioDos** [comment] 2019-05-09 00:04
For new graphs capabilities. I was thinking about bar charts and of course my loved heatmaps. Little joke!!
It would be interesting to get something like this por a period.
![Normales climatológicas 1981-2010 para Buenos Aires](https://user-images.githubusercontent.com/4549674/57416028-c1351e00-71d4-11e9-858f-e746b259255c.png)

**Comment by poblabs** [comment] 2019-05-09 01:13
For something like the combined chart you can do something like it but not exact. This is because you cannot specify the x axis labels at this time. So instead of having 12 months, it would show the full 365 day timeline. 

Here's an example with what you can do today. 

![image](https://user-images.githubusercontent.com/3484775/57420507-d8c0d680-71d5-11e9-9df6-198e3695cbe6.png)

The code:

```
[test]
    show_button = true
    button_text = Today
    title = This Year
    type = spline
    time_length = year
    aggregate_type = max
    aggregate_interval = 86400 # 1 day
    gapsize = 86400000

    [[chart1]]
        title = Temperature and Rain Accumulation
        [[[outTemp]]]
            name = Temperature Max
            aggregate_type = max
            zIndex = 1
            color = "#fc0404"
            [[[[marker]]]]
                enabled = true
                radius = 3
        [[[outTemp_min]]]
            name = Min Temperature
            observation_type = outTemp
            aggregate_type = min
            zIndex = 2
            color = "#173c6a"
            [[[[marker]]]]
                enabled = true
                radius = 3
        [[[rain]]]
            name = Rain Tips
            type = column
            yAxis = 1
            color = "#438bd6"
```

It does some weird things though and I don't know why. When you hover, the marker gets very big lol - I need to check the settings I guess. 

![image](https://user-images.githubusercontent.com/3484775/57420540-fc841c80-71d5-11e9-8c3a-9b60bd4661da.png)


I think it would be nice to try and aggregate into months on x axis as an option instead of the current timestamp option. I will check into that.

**Comment by HoracioDos** [comment] 2019-05-09 01:58
Cool!! I'll test your example tomorrow.

**Comment by HoracioDos** [comment] 2019-05-09 13:56
I've found a definition for cold waves in our weather service. I was a little bit hidden.
> A cold wave is defined as a period in which the maximum and minimum temperatures are equal or lower than percentile 10 (P10) of historical records, for at least 3 consecutive days. Time periods ar based on semesters (April-August) for cold waves

**Comment by poblabs** [comment] 2019-05-09 15:06
I always wonder if I went about graphs.conf the right way. So far I think it is good but when you want to add new things like custom x axis grouping and x axis category names, thats where I wonder. 

I thought about this idea this morning, about making the config file almost the exact structure of the highcharts container, but it would make the graphs.conf much larger and introduce items which may confuse people. Confusion could mean they remove it, then the graph is broken. 

There's more to it than the highcharts structure too, there's the database information gathering, sorting and grouping. So I think if I try to do something it'll have to be a specific "type", like `type = grouped_x` and then based on the xaxis categories, that would define the number of groups. 

The graphs you show above could be JavaScript with predictable data. But with weewx, we have to gather that data everytime on the archive interval, then re-build the graph everytime. So it's more complex. 

It's more work for me, and it means that things like this have to be requested - but the alternative is a long and confusing configuration file.

**Comment by poblabs** [comment] 2019-05-09 15:09
> A cold wave is defined as a period in which the maximum and minimum temperatures are equal or lower than percentile 10 (P10) of historical records, for at least 3 consecutive days. 

Where is the historical record coming from? The station's history or the government's history?

**Comment by HoracioDos** [comment] 2019-05-09 15:32
Government's history I guess, but taking station's history we should be able replicate it.

**Comment by HoracioDos** [comment] 2019-05-09 15:53
Government's history I guess, but taking station's history we shoud be able replicate it.
I know that all this thing could be quite complex. My first interest was records table only. We can forget about charts. This is just an idea to discuss about. Belchertown skin is perfectly fine right now.

**Comment by dseibel** [comment] 2019-05-10 20:04
going to latch on to this issue about ideas for new graphs.

It would be nice to be able to mirror data around the y-axis.  There is a plug-in for highcharts (https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/2554384-multiple-axis-alignment-control) but I haven't had the time to get it working.  

So to produce a graph like:

![image](https://user-images.githubusercontent.com/8311761/57553576-2c453880-732c-11e9-92fe-4803e3964d1f.png)

I did the following hacks:

in belchertown.js.tmpl


added

```
                // switch series data to negative (so it can be reflected on the 0 y-axis)

                if (s.negative_value){
                  for(var i = 0; i < s.data.length; i++) {
                    var value = s.data[i];
                    s.data[i][1] = -(s.data[i][1])
                  }
                  if (belchertown_debug > 0) {
                      console.log( "negative data is: " + s.data);
                  }
                }
```

in the options.series.forEach(s => { section

and then in graphs.conf

```
[[chart6]]
    title = Energy
    type = column
    [[[totalEnergyConsumption]]]
      stacking = "normal"
      name = Consumed
    [[[totalEnergyImport]]]
      stacking = "normal"
      negative_value = "true"
      name = Imported
      color = '#d33682'
    [[[totalEnergyGenerated]]]
      stacking = "normal"
      name = Generated
      color = '#e4d354'
    [[[totalEnergyExported]]]
      stacking = "normal"
      negative_value = "true"
      name = Exported
      color = '#90ed7d'
```

The graph looks for the most part ok, the downside is that the mirrored values have to be negative to have it show up like this.

**Comment by poblabs** [comment] 2019-05-12 02:11
I had a need to display a chart that had months on the x axis and the observations were aggregated over those month. So I spent some time tonight on this. First I worked on getting my specific chart working, then emulated the [screenshot from your issue above](https://github.com/poblabs/weewx-belchertown/issues/119#issuecomment-490694805). 

Here's my chart I was looking for to show lightning strikes per month this year:

![image](https://user-images.githubusercontent.com/3484775/57576892-25f0b280-7439-11e9-9465-37c533878497.png)

Which led me in to recreating the chart you pasted. Here's what I came up with:

![image](https://user-images.githubusercontent.com/3484775/57576904-6f410200-7439-11e9-86c2-15ef14fa69aa.png)

I think it looks pretty good! I need to finish a few things before I commit it, so maybe in the next day or so you can begin to test this type of chart.

**Comment by HoracioDos** [comment] 2019-05-12 13:34
Wow!! Both charts look very good! I want a dozen! I can launch now my own weather service. Lol!!
I want to add a lightning detector to my old weather station. I found a very simple electronic design in youtube last month. How do you get lightning data? is it an electronic device or from internet?

**Comment by poblabs** [comment] 2019-05-12 14:52
@HoracioDos I [purchased this sensor](https://amzn.to/2E5XtiD) and hooked it up to my Raspberry Pi. There are [a lot of these kinds of boards](https://amzn.to/2YonH7S) out there, just look for AS3935 that is the sensor type for lightning. The SwitchDoc one I have is **VERY** sensitive. I ended up having to make a 12 inch stand to put it on to get it away from the Raspberry Pi electrical noise. It helped but it still picks up noise every few minutes.

Then I used the [weewx AS3935 extension](https://github.com/weewx/weewx/wiki/as3935) to have it added. Really easy! I just got mine about 3 weeks ago so not a lot of data yet.

**Comment by HoracioDos** [comment] 2019-05-12 17:54
Good to know! I'm very tempted now

**Comment by poblabs** [comment] 2019-05-14 01:58
Making more progress. I've added some more new graphing options, which now allow you to graph totals across all years within your database. For example, here's all the rain total since my database started. 

![image](https://user-images.githubusercontent.com/3484775/57665498-181e6700-75ca-11e9-9eaf-46cd7b8d3b1c.png)

```
[rainyears]
    title = Rain Years Title
    show_button = true
    button_text = Rain Years
    type = column
    time_length = all
    xaxis_groupby = year
    aggregate_type = max
    aggregate_interval = 86400 # 1 day

    [[raincharts]]
        title = Historical Rain Totals
        [[[rainTotal]]]
            name = Rain Total
```

This code will be available in 1.0rc8.5, maybe another day or so. Just wanted to share progress.

**Comment by HoracioDos** [comment] 2019-05-14 11:54
Hello Pat! This is amazing! Now we the users must be up to the challenge.

**Comment by poblabs** [comment] 2019-05-14 12:07
@dseibel Haven't forgotten about your request, just been tied up. I took a look at that plugin, and I'm not sure I have the time to get it to work either. Your solution of using negative numbers to mirror the chart seems to be suggested a few other times on the internet for mirrored charts. 

To change the labels to not be negative, [try this solution](https://stackoverflow.com/questions/19342904/how-to-remove-negative-symbol-from-negative-y-axis-on-highcharts-highstock). 

```
    yAxis: {            
        labels: {
            formatter: function() {
                return Math.abs(this.value);
            }
        }
    },
```

Then the tooltip updates:

```
    tooltip: {
        formatter: function() {
            return this.x + '<br/>' + this.series.name + ': ' + Math.abs(this.y);
        }
    },
```

That link I pasted had a jsfiddle example. [I forked it and saved it here, you can see the negative columns have the negative sign removed](http://jsfiddle.net/gp0ewozr/). 

This could be a good addition to the charts as a mirrored column chart. 

I'll look into adding it if you think this is an acceptable solution (I do based off other feedback on highcharts and mirrored charts).

**Comment by poblabs** [comment] 2019-05-14 12:17
@HoracioDos There's all kinds of graphs that can be made now I feel like. I just hope I document it fully and don't forget what I did!

Here's another one. This chart is rain total for every month in my database. This tells me that the rainiest month for me is April, then next rainiest is October. 

The only change was `xaxis_groupby = year` to `xaxis_groupby = month` to group everything into months. 

Also notice that since I did not provide xaxis categories, it used the month numbers from the database. 

```
[rainyears]
    title = Rain Years Title
    show_button = true
    button_text = Rain Years
    type = column
    time_length = all
    xaxis_groupby = month
    aggregate_type = max
    aggregate_interval = 86400 # 1 day

    [[raincharts]]
        title = Historical Rain Totals
        [[[rainTotal]]]
            name = Rain Total
```

![image](https://user-images.githubusercontent.com/3484775/57697086-6b230900-7620-11e9-96fd-e509877685f7.png)

Here in this graph I have the month names now since I defined `xaxis_categories`. 

```
[rainyears]
    title = Rain Years Title
    show_button = true
    button_text = Rain Years
    type = column
    time_length = all
    xaxis_groupby = month
    xaxis_categories = 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
    aggregate_type = max
    aggregate_interval = 86400 # 1 day

    [[raincharts]]
        title = Historical Rain Totals
        [[[rainTotal]]]
            name = Rain Total
```

![image](https://user-images.githubusercontent.com/3484775/57697198-b0dfd180-7620-11e9-9222-d79923ece971.png)

**Comment by HoracioDos** [comment] 2019-05-14 12:40
I will test all of them. Thanks! Regarding to all these changes, something has been bouncing in my mind since last week. When you announce this new release in weewx forum. It will be quite a ride.

**Comment by poblabs** [comment] 2019-05-14 12:41
@HoracioDos I agree! That's why once I am done adding new things I need to document, document, document. I think I will add a freeze soon on new features so I can focus on documentation.

**Comment by HoracioDos** [comment] 2019-05-14 12:55
I agree. Some request should be left for future releases. It's the only way to deploy/launch/deliver this release. You know best, short iterations and move on.

**Comment by 41south** [comment] 2019-05-14 13:49
Yes agree, no new features, perhaps just any bug fixes

Somehow the best Weewx skin just continues to get better!  :)

**Comment by dseibel** [comment] 2019-05-14 13:58
@poblabs Thanks for taking a look, and I agree that does look like an acceptable solution!  Thanks for all your work on this skin!

**Comment by poblabs** [comment] 2019-05-14 14:56
@dseibel Do you think it should be `mirrored_value = trur` instead of `negative_value` in the graphs.conf?

**Comment by dseibel** [comment] 2019-05-14 15:42
Yes that actually makes more sense

**Comment by poblabs** [comment] 2019-05-14 19:58
@HoracioDos @dseibel Here goes nothing. Pretty big commit... feel free to update your files with the latest, restart weewx and then start making some graphs with some of the sample code above. 

For the mirrored chart, here's a sample config that worked for me. I used the same observation twice since I don't have solar or anything that I'd mirror. 

```
[mirroredtest]
    title = Mirrored Graph groupby Test
    show_button = true
    button_text = Mirrored Graph groupby Test
    type = column
    time_length = all
    xaxis_groupby = month
    xaxis_categories = 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
    aggregate_type = max
    aggregate_interval = 86400 # 1 day

    [[rainchartsTop]]
        title = Historical Rain Totals for all Months
        [[[rainTotal]]]
            name = Rain Total
            stacking = normal
        [[[rainTotal_bottom]]]
            name = Rain Total
            observation_type = rainTotal
            mirrored_value = true
            stacking = normal
```

![image](https://user-images.githubusercontent.com/3484775/57727990-ca087280-7660-11e9-8efa-c0824ce87db9.png)

---

```
[mirroredtest1]
    title = Mirrored Graph Test
    show_button = true
    button_text = Mirrored Graph Test
    time_length = today
    gapsize = 300000

    [[raincharts]]
        title = Mirrored Chart Test
        [[[rainTotal]]]
            name = Rain Total
        [[[rainTotal_reverse]]]
            name = Rain Total
            observation_type = rainTotal
            mirrored_value = true

    [[rainchartscol]]
        title = Mirrored Chart Test
        [[[rainTotal]]]
            name = Rain Total
            type = column
            stacking = normal
        [[[rainTotal_reverse]]]
            name = Rain Total
            observation_type = rainTotal
            mirrored_value = true
            type = column
            stacking = normal
```

![image](https://user-images.githubusercontent.com/3484775/57728098-0dfb7780-7661-11e9-9c7e-b4bc4ccd5181.png)

**Comment by HoracioDos** [comment] 2019-05-14 23:43
Hello Pat.
While adding all the examples above I found by accident that Belchertown generator doesn't fail but it doesn't create graphs either if a graph group name has with a space in the middle. (For example "Bar Charts") . I think that I would be good to warn about it in the wiki.

**Comment by poblabs** [comment] 2019-05-14 23:46
Good catch. This belongs in the wiki, and maybe a way to catch the error.

**Comment by dseibel** [comment] 2019-05-15 20:29
@poblabs The mirrored charts look good!

![image](https://user-images.githubusercontent.com/8311761/57806758-0699a400-771d-11e9-88c8-640788e4966e.png)

And the new options really open up all kinds of graphs.  One thing I noticed when I tried the rain per year example you have above:

```[rainyears]
    title = Rain Years Title
    show_button = true
    button_text = Rain Years
    type = column
    time_length = all
    xaxis_groupby = year
    aggregate_type = max
    aggregate_interval = 86400 # 1 day

    [[raincharts]]
        title = Historical Rain Totals
        [[[rainTotal]]]
            name = Rain Total
```
is the numbers looked suspiciously low to me:

![image](https://user-images.githubusercontent.com/8311761/57806901-58422e80-771d-11e9-889b-c7830ac9696e.png)


I did a bit of digging and the numbers in the chart are in inches, which are accurate values.  However as you can see on the graph the units are in mm (and all of my other rain graphs use mm and look ok).

**Comment by poblabs** [comment] 2019-05-15 21:04
OH good catch! I'm not converting them in the new xaxis groupby chart. I'll work on that

**Comment by HoracioDos** [comment] 2019-05-15 22:11
Hello everyone!!
I have a request that I'm afraid to ask. My database is not old enough to generate months or year graphs. So I humbly ask if someone could share here weewx database. Simulator driver takes a lifetime to generate records from a previous date.
Thanks in advance

**Comment by poblabs** [comment] 2019-05-16 00:20
@HoracioDos You can put Simulator into SPEED BOOST mode. Here's how, set it to `mode = generator`

Set your start date if you want to start back in time and generate records up to now. 

I have a VERY LARGE 10 year database from Simulator. 

Restart weewx and open your syslog, you should see it add a lot of entries 😃 

```
[Simulator]
    # This section is for the weewx weather station simulator
    
    # The time (in seconds) between LOOP packets.
    loop_interval = 2.5
     
    # The simulator mode can be either 'simulator' or 'generator'.
    # Real-time simulator. Sleep between each LOOP packet.
    #mode = simulator
    # Generator.  Emit LOOP packets as fast as possible (useful for testing).
    mode = generator
    
    # The start time. Format is YYYY-mm-ddTHH:MM. If not specified, the default 
    # is to use the present time.
    #start = 2011-01-01T00:00
    
    # The driver to use:
    driver = weewx.drivers.simulator
```

**Comment by HoracioDos** [comment] 2019-05-16 00:25
I've already done that (generator) many times and it takes a lot of time. I will setup a second pi just to create a dummy database with "old" records.

**Comment by poblabs** [comment] 2019-05-16 01:07
@dseibel Just added the converter - grab the latest belchertown.py and upload it to your system. Restart weewx and see if those xaxis groups convert correctly. Let me know the results!

**Comment by dseibel** [comment] 2019-05-16 03:34
I tried the latest belchertown.py file and graphs aren't being generated anymore.  I see this error on the js console

```
Uncaught ReferenceError: chart_group is not defined
    at String.<anonymous> (belchertown.js?1557977450:632)
    at Function.each (jquery.min.js:2)
    at Object.success (belchertown.js?1557977450:571)
    at u (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at k (jquery.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2)
```

**Comment by HoracioDos** [comment] 2019-05-16 12:50
Hmm It is hard to say. If it is very well documented in the wiki, it could bring more order in keywords sections. On the other hand , people won't read the wiki in detail, It might demand too much time in support. If the proper way to upgrade is wiping out previous configurations it wouln't be a problem either. It would be better if you can provide a full weewx.conf example file not ony a skin.conf example when the skin is installed.

**Comment by poblabs** [comment] 2019-05-16 13:09
@dseibel Doesn't mean much to me (not enough info). Looks like maybe a typo or something in your graphs.conf? Have you restarted weewx since installing the updates? Is your site public? Maybe I can take a look?

**Comment by norecords** [comment] 2019-05-16 16:26
Hello there, I can reproduce the same as @dseibel 
No errors in the syslog.
You can see it https://meteo.correns.org/

**Comment by poblabs** [comment] 2019-05-16 17:34
Oh both of you guys need to [update to the latest `belchertown.js` file](https://raw.githubusercontent.com/poblabs/weewx-belchertown/development/skins/Belchertown/js/belchertown.js.tmpl), too. The section that's broken was removed.

**Comment by poblabs** [comment] 2019-05-16 18:24
FYI - I just pushed a big change to move some Extras options to Labels so that they can be translated. So at this point it might make sense to re-download the development branch and install all files.

**Comment by dseibel** [comment] 2019-05-16 18:32
doh, I had downloaded the entire thing 2 days ago and missed your other updates...my bad! 

I downloaded everything again (restarted weewx) and the graphs work, but the values still seem to be in Inches and the label is in mm

![image](https://user-images.githubusercontent.com/8311761/57877804-e7128200-77d5-11e9-9826-9cf95cd47f84.png)


For reference the actual amounts I have on this page:  https://magpie.dantine.ca/weewx/stage/history/

**Comment by poblabs** [comment] 2019-05-16 18:39
Yeah give the new belchertown.py a try?

**Comment by dseibel** [comment] 2019-05-16 18:59
ok updated with new files...still no change.

**Comment by norecords** [comment] 2019-05-16 20:22
For my part updating solved the problem.

**Comment by poblabs** [comment] 2019-05-16 21:01
@dseibel Yeah that's mostly true. Leave the target unit as US, and let the skin do the rest. Are you specifying metric in your weewx.conf?

**Comment by poblabs** [comment] 2019-05-16 21:04
@norecords Your charts are in US (mph, inch). Is that desired?

**Comment by dseibel** [comment] 2019-05-16 21:34
@poblabs yes I have this 

```
    [[Defaults]]

        # The following section determines the selection and formatting of units.
        [[[Units]]]

            # The following section sets what unit to use for each unit group.
            # NB: The unit is always in the singular. I.e., 'mile_per_hour',
            # NOT 'miles_per_hour'
            [[[[Groups]]]]

                group_altitude = meter    # Options are 'foot' or 'meter'
                group_degree_day = degree_C_day    # Options are 'degree_F_day' or 'degree_C_day'
                group_pressure = hPa    # Options are 'inHg', 'mmHg', 'mbar', or 'hPa'
                group_rain = mm    # Options are 'inch', 'cm', or 'mm'
                group_rainrate = mm_per_hour    # Options are 'inch_per_hour', 'cm_per_hour', or 'mm_per_hour'
                group_speed = km_per_hour    # Options are 'mile_per_hour', 'km_per_hour', 'knot', or 'meter_per_second'
                group_speed2 = km_per_hour2    # Options are 'mile_per_hour2', 'km_per_hour2', 'knot2', or 'meter_per_second2'
                group_temperature = degree_C    # Options are 'degree_F' or 'degree_C'


```
Also have this:

```
  [[Belchertown]]
        HTML_ROOT = /var/www/weewx/stage
        skin = Belchertown
        [[[Units]]]
            [[[[Groups]]]]
                group_altitude = meter
                group_degree_day = degree_C_day
                group_pressure = hPa
                group_rain = mm
                group_rainrate = mm_per_hour
                group_speed = km_per_hour
                group_speed2 = km_per_hour2
                group_temperature = degree_C

```

**Comment by poblabs** [comment] 2019-05-16 22:27
Can you post your graph config? I want to try to replicate it, and have you run some sql queries to see what the data is coming out of the database.

**Comment by dseibel** [comment] 2019-05-16 22:38
here you go

```
[rainyears]
    title = Rain Years Title
    show_button = true
    button_text = Rain Years
    type = column
    time_length = all
    xaxis_groupby = year
    aggregate_type = max
    aggregate_interval = 86400 # 1 day

    [[raincharts]]
        title = Historical Rain Totals
        [[[rainTotal]]]
            name = Rain Total
```

**Comment by poblabs** [comment] 2019-05-16 22:41
Run this sql command and see if the output matches your graphs, or if the graphs are different (because they are being converted)?

Assuming you're on sqlite:

`SELECT strftime("%Y", datetime(dateTime, "unixepoch")) as year, IFNULL(sum(rain),0) as obs FROM archive WHERE dateTime >= 1551409500 AND dateTime <= 1557153300 GROUP BY year;`

**Comment by poblabs** [comment] 2019-05-16 22:43
Hmm, I just ran it on a test VM I have for locale testing, it's in US target_unit, but metric skin options, and that sql query matches the graph. So I'm able to replicate this I think.

**Comment by dseibel** [comment] 2019-05-16 22:44
this is the output, but doesn't actually match the graph...interesting...

```
sqlite> SELECT strftime("%Y", datetime(dateTime, "unixepoch")) as year, IFNULL(sum(rain),0) as obs FROM archive WHERE dateTime >= 1551409500 AND dateTime <= 1557153300 GROUP BY year;
2019|0.377952756
```

**Comment by poblabs** [comment] 2019-05-17 15:46
Which makes sense since my first record could be different than yours. Haven't had a chance to look at it yet but hopefully soon

**Comment by poblabs** [comment] 2019-05-17 18:39
@dseibel Does it seem like any conversions are working for you in the graphs? Not just the xaxis_groupby, but any? (I'm thinking not based on some of my testing)

**Comment by dseibel** [comment] 2019-05-17 18:56
Yes the other ones seem to work, e.g. temp is in C and not F and looks good.

**Comment by poblabs** [comment] 2019-05-18 00:32
@dseibel Grab this attached file, copy and replace your belchertown.py and restart weewx and see if it helps. For some reason I had to specify the converter again within the xaxis_groupby because I'm using a SQL query and not the `getSqlVectors()` method. 

It works for me on my test site, let me know and if it works for you I'll commit it. 

[belchertown.zip](https://github.com/poblabs/weewx-belchertown/files/3193464/belchertown.zip)

**Comment by dseibel** [comment] 2019-05-18 02:19
looks good!

![image](https://user-images.githubusercontent.com/8311761/57963402-ff22f800-78e0-11e9-9b1f-408dbaa2daa3.png)

**Comment by poblabs** [comment] 2019-05-18 12:46
@dseibel Great news, just committed those changes.

**Comment by poblabs** [comment] 2019-05-19 01:11
@dseibel Can you paste your full mirrored graph group? I'd like to include it in the wiki as an example of a mirrored chart. Thanks!

**Comment by dseibel** [comment] 2019-05-19 02:23
sure, here you go

```
[[chart6]]
    title = Energy
    type = column
    [[[totalEnergyConsumption]]]
      stacking = "normal"
      name = Consumed
    [[[totalEnergyImport]]]
      stacking = "normal"
      mirrored_value = true
      name = Imported
      color = '#d33682'
    [[[totalEnergyGenerated]]]
      stacking = "normal"
      name = Generated
      color = '#e4d354'
    [[[totalEnergyExported]]]
      stacking = "normal"
      mirrored_value = true
      name = Exported
      color = '#90ed7d'
```

**Comment by poblabs** [comment] 2019-05-19 12:32
Thanks, I'll get that added. Some fun facts that I learned last night about the graphs. You can combine time_length's in a single graph group. Some of the chart generator config code is borrowed from weewx, and it's more powerful than I realize!

For example in the `[day]` group, all charts will follow the `time_length` at the top of the group (typically this is "today" (since midnight)), but you can also have a chart within the today group that can show any other time length. 

In this example below, the temperature chart (`[[chart1]]`) is today since midnight, but the lightning chart (`[[lightninggroupby]]`) has a `time_length` override with the `xaxis_groupby` defined (which is optional), so I'm able to show a "year" chart within the "day" chart. 

Can be confusing when reading about it which is why an example is ideal.

```
[day]
    title = Today
    show_button = true
    button_text = Today
    time_length = today
    tooltip_date_format = "LLL"
    gapsize = 300000
    
    [[chart1]]
        title = Temperature
        [[[outTemp]]]
            zIndex = 1
            name = Temperature
        [[[windchill]]]
        [[[heatindex]]]
        [[[dewpoint]]]
            color = gray
    
    [[lightninggroupby]]
        title = Lightning Strikes This Year
        yAxisLabel = Lightning
        time_length = year
        xaxis_groupby = month
        xaxis_categories = 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'

        [[[lightning_strikes]]]
            name = Lightning
            type = column
            stacking = normal
        [[[avg_distance]]]
            name = Average Distance
            type = column
            stacking = normal
```

![image](https://user-images.githubusercontent.com/3484775/57982232-5c699700-7a10-11e9-838a-420e26eb93f3.png)


This can be a great way to expand the homepage graphs to show all the graphs in the time scales anyone wants. I'll update the wiki with this too!

**Comment by 41south** [comment] 2019-05-19 19:53
My head hurts just thinking about all the possibilities lol

**Comment by HoracioDos** [comment] 2019-05-28 19:40
Hello Pat.
I didn't find a better place to ask. I'm starting to go deeper into graphs. Would you please post graphs.conf section for "Average Climatological Values for 2018"
Thanks!

**Comment by poblabs** [comment] 2019-05-28 22:36
@HoracioDos Sure. I'll add these to the wiki too since I think it's a cool graph. I even added a "This Year Climatological Values" on my own website's front page. 

Here is 2018 climate

```
[2018earclimate]
    title = "Average Climatological Values for 2018"
    show_button = true
    button_text = 2018 Climate
    type = spline
    time_length = year_specific
    year_specific = 2018
    aggregate_type = max
    aggregate_interval = 86400 # 1 day
    gapsize = 86400000
    xaxis_groupby = month
    xaxis_categories = 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'

    [[chart1]]
        [[[outTemp]]]
            zIndex = 1
            name = Max Temperature
            color = red
        [[[outTemp_min]]]
            name = Min Temperature
            observation_type = outTemp
            aggregate_type = min
            color = "#7cb5ec"
        [[[rainTotal]]]
            name = Rain Total
            type = column
            yAxis = 1
            zIndex = -1
            
```

![image](https://user-images.githubusercontent.com/3484775/58516805-429a2380-8177-11e9-8834-cbac582bc549.png)


---

Here's the one for this current year which I have put into my `[day]` group:

```
[day]
    # Chart Timespan Defaults
    title = Today since Midnight
    show_button = true
    button_text = Today
    time_length = today
    gapsize = 300000

    [[avgclimatethisyear]]
        title = "Average Climatological Values for This Year"
        type = spline
        time_length = year
        aggregate_type = max
        aggregate_interval = 86400 # 1 day
        gapsize = 86400000
        xaxis_groupby = month
        xaxis_categories = 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
        [[[outTemp]]]
            zIndex = 1
            name = Max Temperature
            color = red
        [[[outTemp_min]]]
            name = Min Temperature
            observation_type = outTemp
            aggregate_type = min
            color = "#7cb5ec"
        [[[rainTotal]]]
            name = Rain Total
            type = column
            yAxis = 1
            zIndex = -1
```

![image](https://user-images.githubusercontent.com/3484775/58516860-6eb5a480-8177-11e9-9522-f431d4ef042e.png)

**Comment by HoracioDos** [comment] 2019-05-28 22:46
Thank you very much!
I think you might include something about connectNulls in Graphs Wiki. It can save you a lot of trouble later.

**Comment by poblabs** [comment] 2019-05-28 22:47
I agree. There are a lot of things missing in that wiki I am afraid 😞 but it's ok, i will update it as they come to mind!

**Comment by HoracioDos** [comment] 2019-05-28 22:55
> It's pretty cool to change timespans for an individual chart within the larger group!
Yes, that's a very cool one. You must be proud about all this.

**Comment by poblabs** [comment] 2019-05-28 23:52
> > It's pretty cool to change timespans for an individual chart within the larger group!
> 
> Yes, that's a very cool one. You must be proud about all this.

I am! - although some of the code foundation on things like the rolling up of config to higher tiers within the `.conf` comes from weewx code - so I can't take FULL credit 😃

**Comment by poblabs** [comment] 2019-05-29 12:34
@HoracioDos I have updated [the wiki with the `connectNulls`](https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation#connectnulls) and some other settings [as well as a new table of contents](https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation#introduction). Let me know if you see other things that should be added and updated.

**Comment by ebonzl** [comment] 2019-06-02 22:38
Have ordered a AS3935 for my Raspberry Pi, looking forward to fitting that - hope the lightning graphs etc. get added to this excellent skin in the future!

**Comment by slvrscoobie** [comment] 2019-06-02 22:53
I just ordered one too! (well actually a free sample! :D) so I hope WeeWx / Belchertown will support it soon!

**Comment by poblabs** [comment] 2019-06-02 22:58
Belchertown supports it. check the graphs on my website ;)
https://belchertown weather.com

**Comment by ebonzl** [comment] 2019-06-02 23:05
Looks great! - tho I noticed my site doesn't have the wind rose, solar or the climatalogical graphs. Although TBH I can't remember if I ever had solar from WeeWX, My station provides it tho.

**Comment by 41south** [comment] 2019-06-02 23:26
Just add them in, it's all very easy now. I think the wiki has all the
prerequisites for things like the maxsolar readings. But yell if you need a
hand. On my site I also now record my air quality monitor - still a work in
progress though :)

Colin
41south.net.nz

**Comment by ebonzl** [comment] 2019-06-02 23:34
Ah yes found it, my bad - still feeling my way around v1 ;)

**Comment by poblabs** [comment] 2019-06-02 23:46
To provide more clarity on the AS3935 and Belchertown being ready for it. The skin can chart anything inside the weewx database. So once you get the AS3935 working with your database, you would just specify that column name from the database as the "thing to graph" and it'll do the rest. So this could be the lightning sensor, a soil moisture sensor, or even solar panel usage - as long as weewx has a way to get to that database, then the charts can graph it. 

For the live updated UV and radiation on the front page you would want to update the `station_observations` setting inside skin.conf. You can re-order them, add or remove others. Again, this has to be the name of something in the database. More info is here on the readme. https://github.com/poblabs/weewx-belchertown#general-options

If you find areas where documentation needs help (I'm sure there's a lot of that), let me know!

**Comment by poblabs** [comment] 2019-06-03 01:24
For the AS3935 lightning sensor, a word of advice. It's is **extremely** sensitive. Plan for a way to get it at least 12" (30cm) away from any electrical noise (like a raspberry pi, computer monitors, drills in a workshop, etc). Otherwise it'll be so lost in the electrical noise that it'll never "hear" the lightning. I made my own 12" pylon out of a yard stick I had. 

Here's a cropped photo of my setup. The sensor didn't fit inside the blue project box, so I need to get another one. I worry about the tight connections, so that's another thing to update that in the future. 
![image](https://user-images.githubusercontent.com/3484775/58770143-10276680-857b-11e9-9f82-e266db0f29d4.png)

**Comment by ebonzl** [comment] 2019-06-03 01:35
Noted, I have ordered the longest (30cm ) loom cables I could find  :)

**Comment by Stormtracker017** [comment] 2019-06-09 01:39
Here is a work in progress graph for SDR Frequency Error, when using the RTLDavis driver.  Right now it shows only the first five hopping frequencies.  Need to determine if I want to incorporate remaining frequencies into weewx database or develop a stand alone database.
![SDR Freq error](https://user-images.githubusercontent.com/48191231/59153985-cdabd100-8a35-11e9-9997-cb3d0027e8e3.png)

**Comment by poblabs** [comment] 2019-10-18 18:54
Closing as I think most is covered. For the heat and cold wave days, I think that should be a weewx core feature and not a skin feature. Perhaps raise that to the weewx github page!

**Closed by poblabs** 2019-10-18 18:54 UTC
