### ISSUE TITLE
Maximum Solar Radiation way off

### ISSUE THREAD

**Issue by ebonzl** [poblabs/weewx-belchertown#172] opened 2019-06-15 00:13 UTC
Hi there, I realise this may not be a skin issue, or even a weewx issue., but has anyone seen issues with Maximum Solar Radiation in the Solar Radiation and UV Index graph? Mine is way too low - check out https://wwx.centratus.com/weewx/ - am pretty sure its not my sensor as a maximum of 400wm2 in full sunshine even in Winter in NZ seems very low.

Am wondering if this is due to me being located in the Southern Hemisphere and a lat/long calc problem?

Is there anyway to tune/calibrate the MaxSolarRad?

**Comment by poblabs** [comment] 2019-06-15 00:17
You're right, this isn't a skin issue - and might get some better answers from the weewx-user group, but let me see if I can help. If not, may be best to ask there. 

The maxSolarRad comes from the pyephem package, which you must have installed in order for the bell curve to show up. Make sure you have the right latitude and longitude in your weewx.conf since that's what I think aids pyephem in figuring out your details. 

Since you're in NZ, @41south (http://41south.net.nz/) may have some better ideas on this too. He uses the maxSolarRad and hasn't mentioned any issues with his setup. I don't know how far away you two are but his maxSolarRad is peaking around 330. So maybe yours is accurate?

Your radiation sensor seems to be a bit wonky though - don't know if that's expected behavior or not

**Comment by ebonzl** [comment] 2019-06-15 00:37
Its hard to test the sensor right now. Today its a mixture of full sun and clouds (its currently 12:30pm as I write this) so readings are naturally up and down a bit. If anything I think my UV looks more wonky, or at least not very sensitive. Have checked @41south and is showing UV Index of 2 at night (?). I need good local reference data I guess.. Will need to look into this further - perhaps I need a better Weather Station Array. Many thanks

**Comment by poblabs** [comment] 2019-06-15 00:39
Good point, you can jump onto wunderground and check other local PWS' and see what they have. If you still find a deadend, perhaps someone on the weewx-user group may have more insight into it. 

Going to close this (since it's not a skin issue on the surface), but feel free to keep conversation going in this thread if needed!

**Closed by poblabs** 2019-06-15 00:39 UTC

**Comment by 41south** [comment] 2019-06-15 01:29
Yeah my UV sensor has thrown a wobbly but the solar has been ok. I checked
the max solar recently versus one of the calculators online and it seemed
pretty close to me.
