### ISSUE TITLE
Feature request: Dark Mode

### ISSUE THREAD

**Issue by captain-coredump** [poblabs/weewx-belchertown#89] opened 2019-03-29 22:08 UTC
I am using this skin on a wall-mounted 24/7 Android tablet.  Is it possible to make an option to use a dark background with light text, so that the current white background isn't blinding at night in a dark room?

This skin + Amazon Fire 10 Tablet + Fully Kiosk Browser (Android) = $99 color touchscreen console that Davis will never make.

**Comment by poblabs** [comment] 2019-03-30 00:27
I use dark mode everything and I can't believe I hadn't thought of this. I'll try and stuff it into 1.0 as an option - something like dark_mode = 1 (on) or 0 (off).

**Comment by captain-coredump** [comment] 2019-03-30 16:52
I guess that you don't have a 24/7 wall-mounted tablet that's bright enough to serve as a night with the current white background. :-)

I don't know how complex it is, but can you expand the proposed feature just a bit more and make dark_mode=[on/off/auto]?  In auto mode, have it switch to dark_mode at sunset, and back to white background at sunrise.  Both times are already available in the skin, and this is one of my favorite options that Jachym implemented in his Meteotemplate web code.  I think that he (or someone else with a similar feature) ran into logic issues at extreme latitudes where the sun never set (or rose) at certain times of the year, which I only mention as a potential gotcha that will require a few more lines of code for those living in regions with frequent aurora shows.....

**Comment by poblabs** [comment] 2019-03-30 16:56
That'll require a bit of research for me to do and time has been very thin for me lately (weewx nor web design aren't my full time job, just a hobby).

Let me work on a dark mode (which already is showing me my flaws with the skin that I need to clean up), so the dark mode task alone is larger than I thought. Then perhaps 1.1 or something we can figure out how to make the skin timezone aware and can introduce Auto. 

Are you using MQTT Websocket updates? I see the Auto as something that would only fit into that mode (since the static page requires users to refresh it to get updated data anyways)

**Comment by captain-coredump** [comment] 2019-03-30 20:51
Yes, I'm using MQTT Websocket mode on a wall-mounted tablet as a dedicated 24/7 weather station console.  This is probably not a use that you had originally envisioned, but your skin and the MQTT stuff have created the "killer app" that finally gives WeeWX a graphic web console that updates at LOOP packet frequency and not just archive intervals.

One of these days, I'd love to see a "console" mode that drops the headers (since the user [hopefully] knows where they are), moves the data received pinger into a thin gray status bar at the top of the page, and has left/right taps to move between the temperature-row, forecastrow, eq-stats-row, and highcharts-row as a navigation ring of dedicated pages.  Certainly beyond my meek CSS/Jacascript skills, but I can always dream......

**Comment by poblabs** [comment] 2019-03-30 21:24
Your tablet is a bit too big, but I've created a Pi page which fits a Raspberry Pi and a 3.5" screen. You could give this a try on your tablet. Browse to `yoursite.com/pi` and see how it looks. Again, it probably doesn't look great since it wasn't meant for a Fire Tablet, but it does remove the MQTT timeout, and removes the headers and radar. 

This is how I've created a "console" mode for myself and have included it with the skin as a little hidden "bonus". I think there's 2 or 3 people who have told me they're using it. 

Screenshot of the Pi:

![image](https://user-images.githubusercontent.com/3484775/55281874-996ab480-5310-11e9-885d-f931dc812ba5.png)

**Comment by 41south** [comment] 2019-03-30 21:26
That goes along with a request that I have made as well I think :)

**Comment by captain-coredump** [comment] 2019-03-31 00:06
Great minds think alike, @41south!

I saw the Pi page "Easter Egg" a few months ago, and was hoping that it would be the application that finally made me stop regretting the $75 that I spent for an official Pi 7" 800x480 display.

The 7" Amazon Fire Tablet (1024x600) is on sale this week for $35, the 8" (1280x800) for $50, and the 10" (1920x1200) for $100.  By the time that you add a case onto the Pi's display, even the 10" tablet is cheaper...just add the free Android Fully Kiosk Browser that displays web pages full screen.  I'm not a huge fan of Android in my 100% Apple / Pi garden, but you can't beat the wall-mounted screen real estate for the price.

8" version:
![IMG_3016](https://user-images.githubusercontent.com/17728973/55282941-55ce7580-5325-11e9-88fe-569646e54421.jpeg)

10" version:
![IMG_3018](https://user-images.githubusercontent.com/17728973/55282943-68e14580-5325-11e9-9698-5142b9a3fee2.jpeg)

I've had the 7" model running for a few months in portrait mode, and it is serviceable but wouldn't be my choice if it wasn't already in the junk drawer.  I picked up a 10" during the sale this week, and as you can see there's enough screen real estate to display the current observations, radar, almanac, and 8-day forecast without scrolling.

If I could just find the CSS to change the top "Data Received" line into a gray status bar like MacOS/iOS use on the top of their screens, I'd be good until dark_mode is implemented.....

**Comment by poblabs** [comment] 2019-03-31 00:15
Yeah that does look pretty good! 

To tinker with the colors for that bar, Try changing [this section](https://github.com/poblabs/weewx-belchertown/blob/master/skins/Belchertown/style.css#L1551-L1555).

(UNTESTED) You'll want to add something like `background-color: lightgrey` or something.

**Comment by captain-coredump** [comment] 2019-04-01 00:22
I made a copy of all relevant files to create my own tablet.html, where I could tinker with the CSS and chop the headers off without breaking the original skin.  I told the Fully browser to scale up the fonts to 110%, which was just enough to make the Records section fall off the bottom of the screen.  Hanging on the wall now:

![IMG_3019](https://user-images.githubusercontent.com/17728973/55296971-c7262b00-53ee-11e9-9a4a-cfd6e9410852.jpeg)

Without the browser font scaling, there is enough room at the bottom of the screen to include a row of faux buttons (think tab bar on the bottom) to jump between different sections of the page to mimic the real buttons used on several vendors' dedicated consoles.  I can live with the above until dark_mode is implemented, though.....

**Comment by 41south** [comment] 2019-04-01 00:37
Great work, I like it 👍

**Comment by poblabs** [comment] 2019-04-01 19:09
If you're following the [1.0 development trunk](https://github.com/poblabs/weewx-belchertown/tree/development), you'll see I just pushed a bit update that includes dark mode. This is a combination of Bootstrap's darkly, and Highcharts Dark Unica themes. I also applied some overrides to both of those to keep the skin consistent. Thankfully those frameworks exist which made integration easier. 

Still things that need to happen are:

- [ ] option for 100% dark mode
- [ ] option to enable time aware switching
- [ ] time aware switching if enabled
- [ ] a massive amount of CSS pruning needing to take place

Here's a preview. Obviously my logo is not dark mode ready 😃 

![image](https://user-images.githubusercontent.com/3484775/55352866-e032e880-548f-11e9-96e5-34934de202f2.png)

**Comment by poblabs** [comment] 2019-04-01 19:12
Full screenshot with the graphs:

![image](https://user-images.githubusercontent.com/3484775/55353134-85e65780-5490-11e9-9bf3-cb643082c931.png)

**Comment by poblabs** [comment] 2019-04-01 21:07
For an "adhoc" dark mode, I could also add in a `?theme=dark` URL variable which would make that current page itself dark (not the whole site).

For example: mysite.com/?theme=dark, but when you click to the graphs page, you'll also need to specify mysite.com/graphs?theme=dark ... 

Setting `dark_mode = 1` in skin.conf or weewx.conf Extras, it'll set the full site dark.

**Comment by 41south** [comment] 2019-04-01 21:11
Would that follow through as you selected different pages, i.e. graphs and
records?

**Comment by poblabs** [comment] 2019-04-01 21:12
Not unless you use `dark_mode = 1`

To make the URL variable follow through, I'll need to use cookies and I'm trying to avoid the use of cookies on this website skin

**Comment by 41south** [comment] 2019-04-01 21:16
Yeah thought that might be the case and no worries at all. You've done
superb work with this skin Pat :)

**Comment by poblabs** [comment] 2019-04-01 21:18
Thanks! I guess for "tablet" mode this option would work though. You could do something like `mysite.com/?theme=dark` as an example. Then the rest of the site for everyone else would be light mode.

**Comment by 41south** [comment] 2019-04-01 21:24
Sounds great to me, hopefully that works for Arthur too, this request is
probably more his than mine

**Comment by captain-coredump** [comment] 2019-04-02 00:09
Your dark_mode screen shots above are even more awesome than I envisioned!  Kudos!

I'll grab the 1.0 development branch after work tomorrow, and will let you know how it works out on the tablet.

Thank you for making this happen so fast!!!

**Comment by poblabs** [comment] 2019-04-02 01:05
FYI - 1.0 requires an uninstall of the current skin, and a fresh install of the development branch. Also the charts are 110% changed up, so it's up to you if you want to make the leap with little to no documentation...  We're working on documentation now though, couple more days maybe?

**Comment by poblabs** [comment] 2019-04-02 01:20
I'm also planning on pushing more changes to the charts too. There's some color inconsistencies now with the dark mode that I need to resolve.

**Comment by captain-coredump** [comment] 2019-04-02 08:40
OK, I'll be patient for another week.  The current setup is totally serviceable for now, so I'll try to convince my brain that there's no rush.....

**Comment by poblabs** [comment] 2019-04-02 23:38
Pending any bugs that come out of testing over the next few days, this request will be closed. Dark mode is officially implemented, URL variable implemented, and auto mode for sunset/sunrise also implemented and working. 

You can preview it here: https://belchertownweather.com/?theme=dark

**Comment by 41south** [comment] 2019-04-02 23:43
Awesome work, thanks Pat!

**Comment by slvrscoobie** [comment] 2019-04-03 01:49
Looks GREAT! Cant wait! I tried to install it, but without the official release, Im stuck lol

**Comment by 41south** [comment] 2019-04-03 02:07
You should be able to download the development zip file and install it the
same way as a release, just change the file name as required. Not sure on
any update "gotchas", Pat will need to jump in on that

**Comment by slvrscoobie** [comment] 2019-04-03 02:10
yep, did that, but it says install.py not found. and it broke my standard install, so I just deleted it and restarted. Ill wait till its 'officially' released.

**Comment by 41south** [comment] 2019-04-03 02:29
Hmm, install.py is in there. Did you use sudo when you ran the install
command? I have had similar errors before when I forgot to use sudo

sudo wee_extension --install development.zip I think is what it would
be (or whatever file name you gave it)

**Comment by slvrscoobie** [comment] 2019-04-03 11:58
I ran : 
pi@raspberrypi:~/Downloads $ sudo wee_extension --install weewx-belchertown-development.zip

**Comment by poblabs** [comment] 2019-04-03 11:59
@slvrscoobie Interesting! I think you found a typo of mine? Let me see if I can figure that error out.

**Comment by poblabs** [comment] 2019-04-03 12:00
@slvrscoobie Yep, I forgot a comma in install.py. Oops. Download the development zip file again and try again

**Comment by slvrscoobie** [comment] 2019-04-03 12:15
Cue Michael Bolton
‘I always do that. I always mess up some mundane detail!’
:)
Or is that overplayed?

**Comment by poblabs** [comment] 2019-04-03 12:17
hah so true. Commas and semi-colons are the bane of my coding existence. You'd think I'd learn my lesson by now.

**Comment by captain-coredump** [comment] 2019-04-03 13:53
> Cue Michael Bolton ‘I always do that. I always mess up some mundane detail!’ :) Or is that overplayed?
> 

You have a long way to go until you're in Captain Coredump's league!  My birthday is February 30th or March 32nd (depending on if it is a lap year), and on a scale of 1-10 I'm a 257 at breaking code..... :-)

**Comment by poblabs** [comment] 2019-04-04 00:10
I just pushed a rather large update which increases the speed and reliability of dark mode and auto dark mode through a full re-write of how it's done. There's pros and cons of both methods, but I believe this new method in https://github.com/poblabs/weewx-belchertown/commit/45a76777e0dd7dcfd8f10fdf55df7569f973f993 is more reliable. 

Previous method was to replace the stylesheet all together (pro: less files to load, con: the elements on screen get jumpy when switching, and it was a lot of code to make this happen), this new method just changes the body class (pro: it's less code and it's a seamless and super smooth theme switching. con: users will load dark mode CSS file even if they don't use dark mode). 

It changes a lot within the skin and even renames a file, so if you're testing 1.0 right now please uninstall, delete everything in your HTML folder, reinstall and restart weewx. Everything should populate again at the next archive interval (or run wee_reports if you're impatient)

New notable addition is the toggle switcher at the top right which can change the theme adhoc by clicking the toggle. This can be disabled with an [[[Extras]]] option (to be documented later). 

![image](https://user-images.githubusercontent.com/3484775/55520729-9262df80-564b-11e9-82a5-5d92cb5de352.png)

This toggle button does not persist the theme yet, it only changes the theme on the active page right now. Much like the URL option of `/?theme=dark`. The toggle button persist option may come tomorrow. URL theme setting will remain on the active page only (unless there's a reason for it to persist too, but I don't see one right now since there's the toggle. ). 

Also since this is development, expect other tweaks and fixes throughout the days ahead.

**Comment by poblabs** [comment] 2019-04-04 01:15
Also, if the toggle slider button doesn't make sense, I could use an icon like this one: 🌓

**Comment by 41south** [comment] 2019-04-04 03:00
I think my vote goes from the toggle switch, but the icon is kinda cool
....... Hmmmm

**Comment by poblabs** [comment] 2019-04-04 11:53
I like the slider too. I'll leave it with that for now.

**Comment by poblabs** [comment] 2019-04-04 23:42
A question for the group: right now the toggle switch changes the theme for that page only. If you browse away it will go back to the site-owner's preference on theme. 

If the theme is set to auto then the automatic process will override your toggle when it runs. It runs at weewx archive interval. 

I can make the toggle setting persist, which means that if you're on the about page and you click to go to dark mode, then go to the records page it'll still stay dark mode. 

If auto-mode is on, it will override your toggle preference back to auto mode. 

This gets confusing but the end result is (for example during the day time): "hey that's not what I wanted it to do, I wanted dark mode why is it back to light mode?". 

There's no easy answer here on what the "right way" is to do this. Some thoughts:

1. I could make the toggle persist and "turn off" auto mode. The only way to turn auto mode back on would be for the user to quit the browser (not the tab). 

2. If the theme is on auto I could remove hide the toggle so there's no option to get into a mixed mode. 

Thoughts?

**Comment by michaelundwd** [comment] 2019-04-05 08:25
Not sure if I understood when the changes take place fully, but how about a 3-way switch? Light/Auto/Dark

All 3 positions apply to all pages, and the change occurs at the next archive interval.  Does that work?

Michael

**Comment by 41south** [comment] 2019-04-05 09:29
I think that would be my thought too, dark-light-auto

**Comment by poblabs** [comment] 2019-04-05 11:57
A 3-way switch, while not impossible, wouldn't be my choice. The toggler is basically a checkbox (so on/off), and a 3 way code is a bit more complicated checkbox. It's more code and goes against my "keep it simple" mentality. Plus there's not a lot of room to put text there to describe which position the switch is in. I did consider a 3 way switch, but right now am deciding against it.

**Comment by 41south** [comment] 2019-04-05 21:01
Fair call. I think a mixed mode would be annoying. If I switch to dark then
follow through with the whole site, disable auto as you said until the
browser is closed. I think in my mind that is the best alternative.

**Comment by captain-coredump** [comment] 2019-04-06 00:13
I just grabbed the development branch and installed it.  When running wee_reports to force a skin rebuild, it threw build errors until both of these were added to weewx.conf:

            highcharts_show_apptemp = 0
            highcharts_show_intemp = 0

Neither were in my weewx.conf file, and I'm not sure why I needed to add them when both are showing 0 as the default value in readme.MD.

I'm also not sure why only four of the six graphs are showing up, but that's not a huge concern since the readme.MD file is probably still not current and I didn't touch my weewx.conf file's 0.91 config except for the two lines above.

In case anyone wants a preview, here's my home server set with theme=dark.  Note that I'm not forwarding MQTT outside of my house, so the readings won't update live:

[http://ae3.homelinux.net:845/weewx/live/](http://ae3.homelinux.net:845/weewx/live/)

**Comment by poblabs** [comment] 2019-04-06 00:17
They shouldn't have been added to your weewx.conf. Nothing in the skin gets added to the weewx.conf except for the enablement of the skin. 

Those particular variables are from 0.9.1 and prior and were removed weeks ago. Did you add them previously and don't recall?

In any event, you can remove them. They are deadwood with 1.0+. 

1.0 ships with only 4 graphs now. Basically the whole purpose for 1.0 was a chart system re-write. It's 100% rebuilt from the ground up. This gives you almost 100% total control of all graphs. You'll even see the wind graphs combines 2 old graphs into 1. 

@biltmorelaker wrote a great wiki to get started. [Tons and ton and tons of information on the new charts can be found here](https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation). Basically you'll need to copy `graphs.conf.example` to `graphs.conf` then start editing the charts to your hearts content. 

Dark mode looks good! Still more tweaks coming in the next few days. Trying to make this to-do list go away but it seems never-ending.

**Comment by captain-coredump** [comment] 2019-04-06 00:25
Those two lines were NOT in my weewx.conf file, and wee_reports threw build errors until I added both tonight.

` root@wxpi3plus:~# wee_reports
Using configuration file /etc/weewx/weewx.conf
Generating for all time
Traceback (most recent call last):
    [[Belchertown]]
  File "/usr/share/weewx/weewx/reportengine.py", line 204, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 300, in start
    self.run()
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 160, in run
    ngen = self.generate(gen_dict[section_name], self.gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 234, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 234, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 322, in generate
    default_binding)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 374, in _getSearchList
    searchList += obj.get_extension_list(timespan, db_lookup)
  File "/usr/share/weewx/user/belchertown_highchartsSearchX.py", line 83, in get_extension_list
    if belchertown_skin_dict['Extras']['highcharts_show_apptemp'] == "1":
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'highcharts_show_apptemp'

`root@wxpi3plus:/etc/weewx# wee_reports
Using configuration file /etc/weewx/weewx.conf
Generating for all time
Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 204, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 300, in start
    self.run()
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 160, in run
    ngen = self.generate(gen_dict[section_name], self.gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 234, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 234, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 322, in generate
    default_binding)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 374, in _getSearchList
    searchList += obj.get_extension_list(timespan, db_lookup)
  File "/usr/share/weewx/user/belchertown_highchartsSearchX.py", line 94, in get_extension_list
    if belchertown_skin_dict['Extras']['highcharts_show_intemp'] == "1":
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'highcharts_show_intemp'`

**Comment by captain-coredump** [comment] 2019-04-06 00:28
Maybe something from 0.91 was left behind when I installed the new stuff?

**Comment by poblabs** [comment] 2019-04-06 00:29
Ok I see what's going on. It does not look like you uninstalled the old version with `wee_extension --uninstall Belchertown`. 

1.0 erases A LOT OF FILES. I suggest the following: 

1. Backup your weewx.conf just in case. 
2. `wee_extension --uninstall Belchertown`
3. Delete everything in your HTML folder for Belchertown
4. `wee_extension --install belchertown.zip` (the development one)
5. Make sure you weewx.conf [Belchertown] skin section has all your custom options (you can remove thos ehighcharts_show_intemp and apptemp)
6. Restart weewx. 
7. Wait for an archive interval, or run `wee_reports` to kick off a new report.

**Comment by 41south** [comment] 2019-04-06 00:32
I was going to ask about the upgrade path from 0.9.1 to 1.0 so that answers
it nicely :)

And a great writeup on the new charts! Thanks for the link to that, I
hadn't seen it. Off to read before I tackle the upgrade - probably tomorrow

**Comment by captain-coredump** [comment] 2019-04-06 14:51
Check my sanity here, because I just tried the install again and it still fails unless those two values above are defined in weewx.conf.

With WeeWX stopped, I downloaded a full .zip of the development branch, using this command:

wget -O weewx-belchertown-development.zip https://github.com/poblabs/weewx-belchertown/archive/development.zip

Uninstall current skin:

wee_extension --uninstall Belchertown

Delete any remnants (on a Raspberry Pi, YMMV for other platforms):

rm -r /etc/weewx/skins/Belchertown
rm -r /var/weewx/reports/belchertown
(rm -r /var/weewx/reports/live on my platform as well)

Install new skin package from above:

wee_extension --install weewx-belchertown-development.zip

The only change from my running 0.91 weewx.conf was adding theme = dark, and to fix my non-default Belchertown HTML_ROOT which was defaulted by the installer.  (FWIW, I'm *not* using Belchertown as my default skin if that matters.)

After starting weewx, running wee_reports still fails:

> root@wxpi3plus:~# wee_reports
> Using configuration file /etc/weewx/weewx.conf
> Generating for all time
> Traceback (most recent call last):
>   File "/usr/share/weewx/weewx/reportengine.py", line 204, in run
>     obj.start()
>   File "/usr/share/weewx/weewx/reportengine.py", line 300, in start
>     self.run()
>   File "/usr/share/weewx/weewx/cheetahgenerator.py", line 160, in run
>     ngen = self.generate(gen_dict[section_name], self.gen_ts)
>   File "/usr/share/weewx/weewx/cheetahgenerator.py", line 234, in generate
>     ngen += self.generate(section[subsection], gen_ts)
>   File "/usr/share/weewx/weewx/cheetahgenerator.py", line 234, in generate
>     ngen += self.generate(section[subsection], gen_ts)
>   File "/usr/share/weewx/weewx/cheetahgenerator.py", line 322, in generate
>     default_binding)
>   File "/usr/share/weewx/weewx/cheetahgenerator.py", line 374, in _getSearchList
>     searchList += obj.get_extension_list(timespan, db_lookup)
>   File "/usr/share/weewx/user/belchertown_highchartsSearchX.py", line 83, in get_extension_list
>     if belchertown_skin_dict['Extras']['highcharts_show_apptemp'] == "1":
>   File "/usr/lib/python2.7/dist-packages/configobj.py", line 554, in __getitem__
>     val = dict.__getitem__(self, key)
> KeyError: 'highcharts_show_apptemp'

It is having a problem because highcharts_show_apptemp and company do not exist in weewx.conf?  Putting both in there =0 seems to stop the error...

**Comment by poblabs** [comment] 2019-04-06 14:57
The old chart system, which was a "sub-skin" called `Highcharts_Belchertown`, is still being referenced somewhere. That's the problem. 

Let's start fresh again with the uninstall and manually deleting files after manual verification. 

Uninstall with the `wee_extension --uninstall Belchertown` command again. Run `wee_extension --list` to make sure weewx thinks it's gone. 

Once done, manually check the skins folder for `Belchertown` and `Highcharts_Belchertown`. Delete any or both folder if they still exist. 

Then go to your user/bin folder. Delete `belchertown.py` and delete `belchertown_highchartsSearchX.py`. 

Then edit your weewx.conf and remove `[[Belchertown]]` and remove `[[Highcharts_Belchertown]]` skin sections from the report section. 

Then when that is done, re-run your wget (because I just pushed another change), and install the zip file from wget.

**Comment by captain-coredump** [comment] 2019-04-06 14:57
I found the wee_reports issue.  I had commented out the Highcharts_Belchertown section in weewx.conf, and somehow lost that change somewhere along the line.  wee_reports runs cleanly now!

**Comment by poblabs** [comment] 2019-04-06 15:00
Fantastic! 

When the skin is released I plan on putting bullet points on the above to make sure those who are upgrading have everything Belchertown removed first (the skin and the sub-skin), the bin/user files, and the weewx.conf is cleaned, then a clean reinstall and config of the new skin.

**Comment by poblabs** [comment] 2019-04-06 15:02
Also @captain-coredump fair warning, I'll be pushing another commit in a couple of hours for the auto dark mode. This one's been finicky but I think I have it now. I'm waiting for my simulated "sunrise" to happen in an hour (at Noon) to see it go back to light mode 😄

**Comment by captain-coredump** [comment] 2019-04-06 15:43
From where I'm at now (with all of the v1.0 conversion pain points resolved), a new installer package is only a command away: :-)

wget -O weewx-belchertown-development.zip https://github.com/poblabs/weewx-belchertown/archive/development.zip

I still need to make a few tweaks to the headers to remove the banner info for tablet mode (since that's valuable pixel real estate and I [hopefully!] know where I'm at [FN21vm]), so I'm patiently waiting for the final release version before I copy the relevant files to make my own tablet.html view again.....

**Comment by poblabs** [comment] 2019-04-06 16:09
Even better is that now that you're on 1.0, and I'm still developing it, you can just copy/paste the changes from GitHub without "reinstalling" the theme.

**Comment by poblabs** [comment] 2019-04-12 18:54
Next question about this feature request. Should the auto mode detection be in the station's timezone or in the visitors timezone? 

Currently the settings observes the visitor's timezone. 

For example, I went to @41south's site. He's in NZ, and I'm in US, so I know it's his night time but the site was white for day time since it's day time for me. I guess I was expecting dark mode to match his night time timezone. 

Does it make sense to have the dark mode detection match the stations timezone?

**Comment by biltmorelaker** [comment] 2019-04-12 21:23
My vote is to synchronize it to the visitor's location. My thinking is that dark mode is enabled to look better when the lighting is dim, as it is after sundown. It's not really a signal as to whether the station's time is day or night. Besides the MQTT updates (assuming they use it) show what time it is in the station's timezone.

**Comment by 41south** [comment] 2019-04-12 21:27
I don't think my auto mode detection is working at all, I've never had it
change. Did I miss a config setting? I was thinking maybe it was
implemented yet :)

**Comment by 41south** [comment] 2019-04-12 21:28
Yes I think I agree with that logic. Assuming it means that locally if it's
night for me then it will be dark? I imagine it would be.

**Comment by poblabs** [comment] 2019-04-12 21:34
@biltmorelaker Ok, so your vote is do nothing? (Since it's already in visitor's timezone). Which is perfect to me - less to code 😄 

@41south There's been a few more commits in the last week that should have it working 100% now. I think this time last week I updated almost every file so it could be translated to a new language. So your best bet would be to download the development zip file and copy/paste the files into their homes (you don't need to do a `wee_extension --install` if you don't want to, although you can) and then restart weewx.

**Comment by captain-coredump** [comment] 2019-04-12 21:35
I personally have no preference about local versus station timezone, since
the skin is for my own use at home.  I would assume that you were using station
coordinates to determine sunrise/sunset, but never looked at the code...

-- 
Sent from my iEtch-a-Sketch via subspace

**Comment by poblabs** [comment] 2019-04-12 21:37
I'm actually using weewx's built in sunrise and sunset tags to determine the station's switch time to/from dark mode - detection is based on hour only. 

Ok - I won't make any changes. I'll leave it in the visitors timezone (which is default).

**Comment by 41south** [comment] 2019-04-12 21:39
Sounds logical and definitely a bonus if you don't need to do any more
coding :)

**Comment by 41south** [comment] 2019-04-26 06:48
Just to update this - my site does not change from light to dark mode at
any stage other than using the manual switch on the home page.

**Comment by biltmorelaker** [comment] 2019-04-26 11:57
@41south 

1. Have you updated your site with all of the files from the development branch? 
2. Have you set `theme = auto` in weewx.conf?
3. Have you restarted weewx?

My site reliably changes from light to dark at the hour that sundown occurs (_ex:_ at 6 pm if sundown is between 6:00 pm and 6:59 pm). It changes from dark to light at the hour that sunup occurs (_ex:_  at 7 am if sunup is between 7:00 am and 7:59 am).

**Comment by 41south** [comment] 2019-04-26 17:17
Ah, theme = auto will be the missing part of the puzzle, thanks!

**Comment by biltmorelaker** [comment] 2019-04-26 18:19
Documentation is still thin for V1 😉. The options for `theme `are `light`, `dark `and `auto`. Let us know if the auto change works for you.

**Comment by 41south** [comment] 2019-04-26 18:20
Worked as designed, thank you sir! :)

**Comment by poblabs** [comment] 2019-05-08 14:49
Just pushed a rather large user experience update to dark mode. 

A session is defined as the open tab or the browser. 

When a visitor uses the toggle button, or URL override to switch between light/dark themes, the auto mode is disabled. It cannot be re-enabled during the session.

If you refresh the page, the override will persist. 

If you browse to other pages, the override and selected theme will persist. 

When you close the tab or browser, auto theme will be re-enabled, and all persistent theme overrides will be removed until re-activated. Then this cycle repeats.

**Comment by 41south** [comment] 2019-05-08 17:44
That sounds like a good way to do it. Thanks for the update

Colin

**Comment by poblabs** [comment] 2019-05-08 17:53
Just pushed another update that adds the URL variable of `?theme=auto` which will restore the auto theme mode without having to close the tab. This could be a fringe option that may not get much use, but it's there if needed.

**Comment by poblabs** [comment] 2019-05-08 22:44
I think this wraps up the dark mode request. I'm closing this, but anyone can re-open it if there's a bug or an issue.

**Closed by poblabs** 2019-05-08 22:44 UTC

**Comment by darman16** [comment] 2019-08-09 17:55
> Great minds think alike, @41south!
> 
> I saw the Pi page "Easter Egg" a few months ago, and was hoping that it would be the application that finally made me stop regretting the $75 that I spent for an official Pi 7" 800x480 display.
> 
> The 7" Amazon Fire Tablet (1024x600) is on sale this week for $35, the 8" (1280x800) for $50, and the 10" (1920x1200) for $100. By the time that you add a case onto the Pi's display, even the 10" tablet is cheaper...just add the free Android Fully Kiosk Browser that displays web pages full screen. I'm not a huge fan of Android in my 100% Apple / Pi garden, but you can't beat the wall-mounted screen real estate for the price.
> 
> 8" version:
> ![IMG_3016](https://user-images.githubusercontent.com/17728973/55282941-55ce7580-5325-11e9-88fe-569646e54421.jpeg)
> 
> 10" version:
> ![IMG_3018](https://user-images.githubusercontent.com/17728973/55282943-68e14580-5325-11e9-9698-5142b9a3fee2.jpeg)
> 
> I've had the 7" model running for a few months in portrait mode, and it is serviceable but wouldn't be my choice if it wasn't already in the junk drawer. I picked up a 10" during the sale this week, and as you can see there's enough screen real estate to display the current observations, radar, almanac, and 8-day forecast without scrolling.
> 
> If I could just find the CSS to change the top "Data Received" line into a gray status bar like MacOS/iOS use on the top of their screens, I'd be good until dark_mode is implemented.....

Is there any chance you can send me your files for the fire 8" and 10"? I am new to this and i have been trying to find away to accomplish this.

thanks

**Comment by poblabs** [comment] 2019-08-09 17:57
I think @captain-coredump made those. Feel free to share! 😄

**Comment by captain-coredump** [comment] 2019-08-11 19:08
> Is there any chance you can send me your files for the fire 8" and 10"? I am new to this and i have been trying to find away to accomplish this.

Unfortunately, I have not updated my skin from the pre-1.0 days, because I haven't had a free moment to locate the minor edits that I made for my Fire "kiosk mode" to port them over to the current version files.

You can use the free version of the Android Fully Kiosk Browser on the Fire (available on Google Play if not in the Amazon store), and tinker with font sizes and zooms until the regular pages look good on each tablet.  The responsive web code that POB used does a pretty decent job of making it look good out of the box.

The only significant change that I made was stripping the banner/header at the top, since I know where I'm at (I hope!) when looking at the Fire tablet and that screen real estate is valuable for actual observation data.

Now that the 1.x tree is out the door, I should probably submit a request for a kiosk mode one of these days if it hasn't already been implemented..... ;)

**Comment by darman16** [comment] 2019-08-11 22:25
What program were you using to modify the CSS? The program I was using scrambles everything and it looks a mess. I am using an old version of dream weaver. Sorry for all the questions. I am trying to figure all this out as I go along.

**Comment by captain-coredump** [comment] 2019-08-12 23:01
Me?  I have been using "vi" for everything since the 1980's.....

**Comment by poblabs** [comment] 2019-08-13 01:45
I use Notepad++. I haven't looked at Dreamweaver since... 2005? 😄 

The dark mode CSS file (belchertown-dark.min.css) is just 3 very long lines, so they'll naturally wrap and look weird. 

In Notepad++ the end of line conversion should be set to Windows CR LF
