### ISSUE TITLE
No colors in Windrose

### ISSUE THREAD

**Issue by gcediel** [poblabs/weewx-belchertown#383] opened 2020-09-08 07:07 UTC
Hi.
I've just migrated from stable skin to development, and I find that the windrose is only shown in black colors. I uninstalled the previous skin, and installed the developemente one, so there are no files from the previous version.
Any suggestions?
Thanks in advance.
Best regards,

**Comment by poblabs** [comment] 2020-09-08 13:59
Do you have a link to your site? Can you attach your graphs.conf?

**Comment by gcediel** [comment] 2020-09-08 14:06
Hello.
You can access it in https://www.elbor.org/weather/
This is my graphs.conf (note that it was the same used with the stable release, and the colors were ok):
```
# Global Chart Defaults
# These are fallback options that charts will use if an option is not defined. 
aggregate_type = None
time_length = 90000 # Last 25 hours
type = line
colors = "#7cb5ec, #b2df8a, #f7a35c, #8c6bb1, #dd3497, #e4d354, #268bd2, #f45b5b, #6a3d9a, #33a02c"
tooltip_date_format = "LLL"
credits = www.elbor.org
credits_url = https://www.elbor.org

[homepage]
    # Chart Timespan Defaults
    title = "Condiciones actuales"
    show_button = true
    button_text = "Condiciones actuales"
    time_length = 90000
    tooltip_date_format = "LLL"
    gapsize = 300000 # This should be your archive_interval from weewx.conf multiplied by 1000 to get milliseconds. Standard is 5 minutes

    [[chart1]]
        title = Temperatura
        [[[outTemp]]]
            name = Exterior
            yAxis_tickInterval = 1
        [[[extraTemp1]]]
            name = 1wire
            zIndex = 1
        [[[extraTemp2]]]
            name = Máx Máx
            lineWidth = 1 
            zIndex = 2
            color = "#f83800"
       [[[extraTemp3]]]
            name = Máx Pro
            lineWidth = 1
            zIndex = 2
            color = "#f86000"
       [[[extraTemp4]]]
            name = Máx Mín
            lineWidth = 1
            zIndex = 2
            color = "#f89800"
       [[[extraTemp5]]]
            name = Mín Máx
            lineWidth = 1
            zIndex = 2
            color = "#b0b8e0"
       [[[extraTemp6]]]
            name = Mín Pro
            lineWidth = 1
            zIndex = 2
            color = "#8898d8"
       [[[extraTemp7]]]
            name = Mín Mín
            lineWidth = 1
            zIndex = 2
            color = "#5070c8"

    [[chart1b]]
        title = Condiciones
        [[[windchill]]]
            name = Sensación térmica
            yAxis_tickInterval = 1
        [[[heatindex]]]
            name = Índice de calor
            color = "#f7a35c"
        [[[dewpoint]]]
            name = Punto de rocío
            color = purple

    [[chart2]]
        # The combined Wind Chart works best in this configuration
        title = Viento
        yAxis_min = 0
        [[[windDir]]]
            name = Dirección
            zIndex = 2
            yAxis = 1
            yAxis_max = 360
            lineWidth = 0
            [[[[marker]]]]
                enabled = true
            [[[[states]]]]
                [[[[[hover]]]]]
                        lineWidthPlus = 0
        [[[windGust]]]
            name = Rachas
            zIndex = 1
        [[[windSpeed]]]
            name = Velocidad
            type = area

    [[chart2b]]
        title = Rosa de los vientos
        [[[windRose]]]
            beauford0 = “#1278c8
            beauford1 = “#1fafdd
            beauford2 = “#71bc3c
            beauford3 = “#ffae00
            beauford4 = “#ff7f00
            beauford5 = “#ff4500
            beauford6 = “#9f00c5

    [[chart3]]
        title = Lluvia
        [[[rainRate]]]
            name = Tasa
            yAxis = 1
        [[[rainTotal]]]
            name = Lluvia total

    [[chart4]]
        title = Barómetro - Humedad
        type = spline
        [[[barometer]]]
            name = Barómetro
            color = "#BECC00"
            yAxis_tickinterval = 0.01
        [[[outHumidity]]]
            name = Humedad
            yAxis = 1
            yAxis_min = 0
            yAxis_max = 100

    [[chart6]]
        title = Interior
        yAxis_softMin = 15
        yAxis_softMax = 30
        [[[inTemp]]]
            name = Temperatura
            yAxis_tickInterval = 1
        [[[outTemp]]]
            name = Exterior
            lineWidth = 1 
            yAxis_tickInterval = 0.5
       [[[inHumidity]]]
            name = Humedad            
            yAxis = 1
            yAxis_min = 0
            yAxis_max = 100

[day]
    # Chart Timespan Defaults
    title = "Hoy"
    show_button = true
    button_text = "Día"
    time_length = today
    tooltip_date_format = "LLL"
    gapsize = 300000 # This should be your archive_interval from weewx.conf multiplied by 1000 to get milliseconds. Standard is 5 minutes

    [[chart1]]
        title = Temperatura
        [[[outTemp]]]
            name = Exterior
            yAxis_tickInterval = 1
        [[[extraTemp1]]]
            name = 1wire
            zIndex = 1
        [[[extraTemp2]]]
            name = Máx Máx
            lineWidth = 1
            zIndex = 2
            color = "#f83800"
       [[[extraTemp3]]]
            name = Máx Pro
            lineWidth = 1
            zIndex = 2
            color = "#f86000"
       [[[extraTemp4]]]
            name = Máx Mín
            lineWidth = 1
            zIndex = 2
            color = "#f89800"
       [[[extraTemp5]]]
            name = Mín Máx
            lineWidth = 1
            zIndex = 2
            color = "#b0b8e0"
       [[[extraTemp6]]]
            name = Mín Pro
            lineWidth = 1
            zIndex = 2
            color = "#8898d8"
       [[[extraTemp7]]]
            name = Mín Mín
            lineWidth = 1
            zIndex = 2
            color = "#5070c8"

    [[chart1b]]
        title = Temperatura 
        [[[windchill]]]
            name = Sensación térmica
            yAxis_tickInterval = 1
        [[[heatindex]]]
            name = Índice de calor
            color = "#f7a35c"
        [[[dewpoint]]]
            name = Punto de rocío
            color = purple

    [[chart2]]
        # The combined Wind Chart works best in this configuration
        title = Viento
        yAxis_min = 0
        [[[windDir]]]
            name = Dirección
            zIndex = 2
            yAxis = 1
            yAxis_max = 360
            lineWidth = 0
            [[[[marker]]]]
                enabled = true
            [[[[states]]]]
                [[[[[hover]]]]]
                        lineWidthPlus = 0
        [[[windGust]]]
            name = Rachas
            zIndex = 1
        [[[windSpeed]]]
            name = Velocidad
            type = area

    [[chart2b]]
        title = Rosa de los vientos
        [[[windRose]]]
            beauford0 = “#1278c8
            beauford1 = “#1fafdd
            beauford2 = “#71bc3c
            beauford3 = “#ffae00
            beauford4 = “#ff7f00
            beauford5 = “#ff4500
            beauford6 = “#9f00c5
    
    [[chart3]]
        title = Lluvia
        [[[rainRate]]]
            name = Tasa de lluvia
            yAxis = 1
        [[[rainTotal]]]
            name = Lluvia total
    
    [[chart4]]
        title = Barómetro - Humedad
        type = spline
        [[[barometer]]]
            name = Barómetro
            color = "#BECC00"
        [[[outHumidity]]]
            name = Humedad
            yAxis = 1
            yAxis_min = 0
            yAxis_max = 100

    [[chart6]]
        title = Interior
        [[[inTemp]]]
            name = Temperatura
            yAxis_tickInterval = 1
        [[[outTemp]]]
            name = Exterior
            lineWidth = 1
            yAxis_tickInterval = 1
       [[[inHumidity]]]
            name = Humedad
            yAxis = 1
            yAxis_min = 0
            yAxis_max = 100

[week]
    # Chart Timespan Defaults
    title = "Esta semana"
    show_button = true
    button_text = "Semana"
    time_length = 604800 # Last 7 days
    tooltip_date_format = "LLLL"
    aggregate_type = max
    aggregate_interval = 3600 # 1 hour
    gapsize = 3600000 # 1 hour in milliseconds

    [[chart1]]
        title = Temperatura
        [[[outTemp]]]
            name = Exterior
            yAxis_tickInterval = 1
        [[[extraTemp1]]]
            name = 1wire
            zIndex = 1
        [[[extraTemp2]]]
            name = Máx Máx
            lineWidth = 1
            zIndex = 2
            color = "#f83800"
       [[[extraTemp3]]]
            name = Máx Pro
            lineWidth = 1
            zIndex = 2
            color = "#f86000"
       [[[extraTemp4]]]
            name = Máx Mín
            lineWidth = 1
            zIndex = 2
            color = "#f89800"
       [[[extraTemp5]]]
            name = Mín Máx
            lineWidth = 1
            zIndex = 2
            color = "#b0b8e0"
       [[[extraTemp6]]]
            name = Mín Pro
            lineWidth = 1
            zIndex = 2
            color = "#8898d8"
       [[[extraTemp7]]]
            name = Mín Mín
            lineWidth = 1
            zIndex = 2
            color = "#5070c8"

    [[chart1b]]
        title = Temperatura 
        [[[windchill]]]
            name = Sensación térmica
            yAxis_tickInterval = 1
        [[[heatindex]]]
            name = Índice de calor
            color = "#f7a35c"
        [[[dewpoint]]]
            name = Punto de rocío
            color = purple
    
    [[chart2]]
        # The combined Wind Chart works best in this configuration
        title = Viento
        yAxis_min = 0
        [[[windDir]]]
            title = Dirección
            zIndex = 2
            yAxis = 1
            yAxis_max = 360
            lineWidth = 0
            # Here we can override the timespan default aggregate type with our own specific to this chart
            aggregate_type = avg
            [[[[marker]]]]
                enabled = true
            [[[[states]]]]
                [[[[[hover]]]]]
                        lineWidthPlus = 0
        [[[windGust]]]
            title = Rachas
            zIndex = 1
        [[[windSpeed]]]
            title = Velocidad
            type = area

    [[chart2b]]
        title = Rosa de los vientos
        [[[windRose]]]
            beauford0 = “#1278c8
            beauford1 = “#1fafdd
            beauford2 = “#71bc3c
            beauford3 = “#ffae00
            beauford4 = “#ff7f00
            beauford5 = “#ff4500
            beauford6 = “#9f00c5
    
    [[chart3]]
        title = Lluvia
        [[[rainRate]]]
            title = Tasa de lluvia
            yAxis = 1
        [[[rainTotal]]]
            name = Lluvia total
    
    [[chart4]]
        title = Barómetro - Humedad
        aggregate_type = avg
        [[[barometer]]]
            name = Barómetro
            color = "#BECC00"
        [[[outHumidity]]]
            name = Humedad
            yAxis = 1
            yAxis_min = 0
            yAxis_max = 100

    [[chart6]]
        title = Interior
        [[[inTemp]]]
            name = Temperatura
            yAxis_tickInterval = 1
        [[[outTemp]]]
            name = Exterior
            lineWidth = 1
            yAxis_tickInterval = 1
       [[[inHumidity]]]
            name = Humedad
            yAxis = 1
            yAxis_min = 0
            yAxis_max = 100
   
[month]
    # Chart Timespan Defaults
    title = "Este mes"
    show_button = true
    button_text = "Mes"
    type = spline
    time_length = 2592000 # Last 30 days
    tooltip_date_format = "dddd LL"
    aggregate_type = max
    aggregate_interval = 86400 # 1 day
    gapsize = 86400000 # 1 day in milliseconds

    [[chart1]]
        title = Temperatura
        [[[outTemp]]]
            zIndex = 1
            name = Máxima
            color = red
            yAxis_tickInterval = 1
        [[[outTemp_min]]]
            name = Mínima
            observation_type = outTemp
            aggregate_type = min
            color = "#7cb5ec"
        [[[extraTemp2]]]
            name = Máx Máx
            lineWidth = 1
            zIndex = 2
            color = "#f83800"
       [[[extraTemp3]]]
            name = Máx Pro
            lineWidth = 1
            zIndex = 2
            color = "#f86000"
       [[[extraTemp4]]]
            name = Máx Mín
            lineWidth = 1
            zIndex = 2
            color = "#f89800"
       [[[extraTemp5]]]
            name = Mín Máx
            lineWidth = 1
            zIndex = 2
            color = "#b0b8e0"
       [[[extraTemp6]]]
            name = Mín Pro
            lineWidth = 1
            zIndex = 2
            color = "#8898d8"
       [[[extraTemp7]]]
            name = Mín Mín
            lineWidth = 1
            zIndex = 2
            color = "#5070c8"
    
    [[chart2]]
        # The combined Wind Chart works best in this configuration
        title = Viento
        yAxis_min = 0
        [[[windDir]]]
            zIndex = 2
            yAxis = 1
            yAxis_max = 360
            lineWidth = 0
            # Here we can override the timespan default aggregate type with our own specific to this chart
            aggregate_type = avg
            [[[[marker]]]]
                enabled = true
            [[[[states]]]]
                [[[[[hover]]]]]
                        lineWidthPlus = 0
        [[[windGust]]]
            zIndex = 1
        [[[windSpeed]]]
            type = area

    [[chart2b]]
        title = Rosa de los vientos
        [[[windRose]]]
            beauford0 = “#1278c8
            beauford1 = “#1fafdd
            beauford2 = “#71bc3c
            beauford3 = “#ffae00
            beauford4 = “#ff7f00
            beauford5 = “#ff4500
            beauford6 = “#9f00c5
    
    [[chart3]]
        title = Lluvia
        type = line
        [[[rainRate]]]
            name = Tasa de lluvia
            yAxis = 1
        [[[rainTotal]]]
            name = Lluvia total
    
    [[chart4]]
        title = Barómetro - Humedad
        aggregate_type = avg
        [[[barometer]]]
            name = Barómetro
            color = "#BECC00"
        [[[outHumidity]]]
            name = Humedad
            yAxis = 1
            yAxis_min = 0
            yAxis_max = 100

    [[chart6]]
        title = Interior
        [[[inTemp]]]
            name = Temperatura
            yAxis_tickInterval = 1
        [[[outTemp]]]
            name = Exterior
            lineWidth = 1
            yAxis_tickInterval = 1
       [[[inHumidity]]]
            name = Humedad
            yAxis = 1
            yAxis_min = 0
            yAxis_max = 100

[year]
    # Chart Timespan Defaults
    title = "Este año"
    show_button = true
    button_text = "Año"
    type = spline
    time_length = year
    tooltip_date_format = "dddd LL"
    aggregate_type = max
    aggregate_interval = 86400 # 1 day
    gapsize = 86400000 # 1 day in milliseconds

    [[chart1]]
        title = Temperatura
        [[[outTemp]]]
            zIndex = 1
            name = Máxima
            color = red
            yAxis_tickInterval = 1
        [[[outTemp_min]]]
            name = Mínima
            observation_type = outTemp
            aggregate_type = min
            color = "#7cb5ec"
        [[[extraTemp2]]]
            name = Máx Máx
            lineWidth = 1
            zIndex = 2
            color = "#f83800"
       [[[extraTemp3]]]
            name = Máx Pro
            lineWidth = 1
            zIndex = 2
            color = "#f86000"
       [[[extraTemp4]]]
            name = Máx Mín
            lineWidth = 1
            zIndex = 2
            color = "#f89800"
       [[[extraTemp5]]]
            name = Mín Máx
            lineWidth = 1
            zIndex = 2
            color = "#b0b8e0"
       [[[extraTemp6]]]
            name = Mín Pro
            lineWidth = 1
            zIndex = 2
            color = "#8898d8"
       [[[extraTemp7]]]
            name = Mín Mín
            lineWidth = 1
            zIndex = 2
            color = "#5070c8"
    
    [[chart2]]
        # The combined Wind Chart works best in this configuration
        title = Viento
        yAxis_min = 0
        [[[windDir]]]
            name = Dirección
            zIndex = 2
            yAxis = 1
            yAxis_max = 360
            lineWidth = 0
            # Here we can override the timespan default aggregate type with our own specific to this chart
            aggregate_type = avg
            [[[[marker]]]]
                enabled = true
            [[[[states]]]]
                [[[[[hover]]]]]
                        lineWidthPlus = 0
        [[[windGust]]]
            name = Rachas
            zIndex = 1
        [[[windSpeed]]]
            name = Velocidad
            type = area

    [[chart2b]]
        title = Rosa de los vientos
        [[[windRose]]]
            beauford0 = “#1278c8
            beauford1 = “#1fafdd
            beauford2 = “#71bc3c
            beauford3 = “#ffae00
            beauford4 = “#ff7f00
            beauford5 = “#ff4500
            beauford6 = “#9f00c5
    
    [[chart3]]
        title = Lluvia
        type = line
        [[[rainRate]]]
            name = Tasa de lluvia
            yAxis = 1
        [[[rainTotal]]]
            name = Lluvia total
    
    [[chart4]]
        title = Barómetro - Humedad
        aggregate_type = avg
        [[[barometer]]]
            name = Barómetro
            color = "#BECC00"
        [[[outHumidity]]]
            name = Humedad
            yAxis = 1
            yAxis_min = 0
            yAxis_max = 100

    [[chart6]]
        title = Interior
        aggregate_type = avg
        [[[inTemp]]]
            name = Temperatura
            yAxis_tickInterval = 1
        [[[outTemp]]]
            name = Exterior
            lineWidth = 1
            yAxis_tickInterval = 1
       [[[inHumidity]]]
            name = Humedad
            yAxis = 1
            yAxis_min = 0
            yAxis_max = 100
```
Thanks for your attention,

**Comment by poblabs** [comment] 2020-09-08 14:07
If you remove the colors from the windrose, do the default colors start to work again?

```
    [[[windRose]]]
            beauford0 = “#1278c8
            beauford1 = “#1fafdd
            beauford2 = “#71bc3c
            beauford3 = “#ffae00
            beauford4 = “#ff7f00
            beauford5 = “#ff4500
            beauford6 = “#9f00c5
```

**Comment by poblabs** [comment] 2020-09-08 14:10
Also one thing I'm noticing is that you do not have `"` closing the colors tags. Perhaps the problem is there. 

```
            beauford0 = “#1278c8"
            beauford1 = “#1fafdd"
            beauford2 = “#71bc3c"
            beauford3 = “#ffae00"
            beauford4 = “#ff7f00"
            beauford5 = “#ff4500"
            beauford6 = “#9f00c5"
```

**Comment by gcediel** [comment] 2020-09-08 14:20
Oh, it was my fault, sorry.
I think there were two things:
- No closing `"`.
- Also, the `"` used were 'opening quotes'. Maybe I copied the config from some web page (and no closing quotes were pasted?).
Anyway, the weird thing is that the same graphs.conf was working with the stable release.
Many thanks.
Best regards.

**Closed** 2020-09-08 14:24 UTC
