### ISSUE TITLE
Foreign characters not displayed correctly.

### ISSUE THREAD

**Issue by gand07** [poblabs/weewx-belchertown#456] opened 2020-11-03 04:54 UTC
**Describe the bug**
Weewx 4.1.1.
Foreign characters not displayed correctly in graph

**Link to your website (IMPORTANT)**
[http://bornholmervejret.dk/](url)

**Version of the skin you're using**
Version 1.2

**To Reproduce**
See website

**Expected behavior**
Display "Ø" instead of &#216;

**Screenshots**
Attached

**Device Information (please complete the following information):**
 - Device: Desktop, Mobile
 - OS: Windows, IOS
 - Browser Microsoft Edge

**Additional context**
Working in version 1.1

![Untitled](https://user-images.githubusercontent.com/47734099/97950996-e9d1b000-1d98-11eb-8ac4-39f8bc1523d6.jpg)

**Comment by ArendPWS** [comment] 2020-11-04 21:32
Hi Gert,

Besides your issue with the characters I noticed that you also have a problem on the right y-axis. The wind directions are shifting upwards, that must be related to something in your graphs.conf file.

Arend

**Comment by gand07** [comment] 2020-11-05 05:42
Hi Arend

Thanks for catching this. I did a new install of Belchertown and the sequence seems to is right now. The issue the the "Ø" is still there.
![Untitled1](https://user-images.githubusercontent.com/47734099/98202277-f63d4080-1f31-11eb-9053-b9d1a33340c1.jpg)


Gert

**Comment by ArendPWS** [comment] 2020-11-08 12:52
> Hi Arend
> 
> Thanks for catching this. I did a new install of Belchertown and the sequence seems to is right now. The issue the the "Ø" is still there.
> 
> Gert

@gand07 

In your latest picture it is still shifting, but this time downwards. This is because you are missing:

        yAxis_min = 0 and yAxis_max = 360 in some wind charts

Please compare the settings for your wind charts in graphs.conf you should notice the difference.

Here's the graphs.conf.example:

    [[chart2]]
        # The combined Wind Chart works best in this configuration
        title = Wind Speed and Direction
        yAxis_min = 0
        [[[windDir]]]
            zIndex = 1
            yAxis = 1
            yAxis_max = 360
            lineWidth = 0
            [[[[marker]]]]
                enabled = true
            [[[[states]]]]
                [[[[[hover]]]]]
                        lineWidthPlus = 0
        [[[windGust]]]
        [[[windSpeed]]]
            zIndex = 2

Your gapsize is also still on 300000 which you should have changed to 300 with the latest skin version.

These changes are not related to your character problems, I solved that one too, but requires many changes. You can see an example at my test site: [http://hengelo.rf.gd/belchertown/](http://hengelo.rf.gd/belchertown/)

**Comment by gand07** [comment] 2020-11-08 16:09
Hi Arend

Thanks for taking your time to solve this.

I had the values in graphs.conf, but they were all lower case. I have changed them now to yAxis_min = 0 and yAxis_max = 360. I have also changed gap to 300

Your site looks good with the right display of "Ø". Can I also implement that? You wrote, it was a lot of changes.

Thanks again.

Gert
[http://bornholmervejret.dk/](url)

**Comment by ArendPWS** [comment] 2020-11-13 08:40
Hi Gert,

I put all the changes in my fork. These changes do not only apply to the character problem but will also implement all pull requests I created but which are still not implemented. In addition to these PR's there are some other fixes. You can try out this version of the skin if you want to. My fork is here:

[https://github.com/ArendPWS/weewx-belchertown](https://github.com/ArendPWS/weewx-belchertown)

Plase make sure you backup all the relevant files first. You will also need to check all configuration options in skin.conf to support the latest forecast changes (1, 3, 24 hour forecast), a nice add-on created by @michaelundwd.
I have no plans on creating any further pull requests for the standard Belchertown skin. So it's up to you if you really want to use my modified version.

Arend

**Comment by gand07** [comment] 2020-11-14 14:57
Hi Arend

I'll setup a test system and try out the changes.

Thanks for that.

Gert

**Comment by gand07** [comment] 2020-11-17 07:19
Hi Arend
Up and running on my test system. Working well, thanks for that. Hopefully the developer will implement support for foreign characters.

Thanks again

Gert

**Comment by gand07** [comment] 2021-01-03 16:39
Hi Arend
I have just updated to the latest version of Belchertown, now I have problems the Danish characters again. I just thought that your additions were merged into master now.
Can You help me again?

Rgds
Gert

**Comment by gand07** [comment] 2021-01-03 21:51
Hi
Like this:
![Wind](https://user-images.githubusercontent.com/47734099/103489633-39bf0880-4e16-11eb-9a04-6a09afa05123.jpg)

**Comment by ArendPWS** [comment] 2021-01-14 20:11
Hi Gert,

There seems to be no interest in getting some serious issues fixed. So I give up trying (and wasting time) getting these esential updates into the master. I will be around on the weewx forum and maybe will post my updates there in the future using my fork.

Regards, Arend

**Comment by gand07** [comment] 2021-01-14 22:39
Hi Arend

Thank you for your hard work in finding solutions for us, who don't want English language in the template. It is a pity that the changes you have proposed are not included. 

When a new release comes, I will have to manually change belchertown.js.tmpl to display the characters correctly. That will solve some of the issues about foreign characters, but not them all.

Do you still have a version that shows the characters correctly. If you have I will install it and forget about updating in the future.

Gert

**Comment by uajqq** [comment] 2021-01-14 23:57
If someone has code that works, please post it and/or open a pull request so it can be incorporated into the skin! Happy to help if I can.

**Comment by ArendPWS** [comment] 2021-01-17 14:14
@uajqq

Thanks for offering your help, but the problem is that my PRs don't get merged. This skin is lacking communication between the owner of the repo and the users. I understand Pat has limited/no time to spend on his skin. Maybe he should appoint you as a co-owner and delegate. This skin still has some serious issues under the hood and for some of them I have found solutions that I would like tho share. But after submitting several PRs  and no or little response I have given up trying.

You can try to get this one into the master:

Fix for (a)synchronous json updates to prevent units showing undefined #523

Good luck!

Regards, Arend

**Comment by poblabs** [comment] 2021-01-17 15:05
Your PRs can't be merged. They have too many conflicts that I've told you.
You need to only commit the lines relevant to your PR and not ALL changes
against your fork and the master branch.

**Comment by ArendPWS** [comment] 2021-01-17 15:19
PR #533, There are no conflicts according to Github.

**Comment by poblabs** [comment] 2021-01-17 15:21
There are no conflicts according to GitHub, but there are conflicts which would send the skin out of sync. You only need to commit the portions that are changing. Your PR has over 140 lines of changed code which include websocket items (which I don't believe are part of this problem?)

**Comment by poblabs** [comment] 2021-02-16 17:48
Resolved in #577

**Closed by poblabs** 2021-02-16 17:48 UTC
Labels: bug
