### ISSUE TITLE
Post Python3 upgrade error

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#279] opened 2020-05-07 06:17 UTC
Getting this after after moving to Python3

`May  7 18:10:23 raspberrypi weewx[10442] ERROR user.belchertown: Update Checker: Error downloading GitHub Version data. The error is: the JSON object must be str, not 'bytes'`

**Comment by 41south** [comment] 2020-05-07 06:19
And also

```
May  7 18:15:20 raspberrypi weewx[10442] ERROR user.belchertown: Update Checker: Error downloading GitHub Version data. The error is: the JSON object must be str, not 'bytes'
May  7 18:15:22 raspberrypi weewx[10442] ERROR user.belchertown: Update Checker: Error downloading GitHub Version data. The error is: HTTP Error 403: rate limit exceeded
May  7 18:15:23 raspberrypi weewx[10442] ERROR user.belchertown: Update Checker: Error downloading GitHub Version data. The error is: HTTP Error 403: rate limit exceeded
```

**Comment by kacnje** [comment] 2020-05-07 08:00
I have the same problem after upgrade to Weewx 4 (and started with Python3):
` weewx[7283] ERROR user.belchertown: Update Checker: Error downloading GitHub Version data. The error is: the JSON object must be str, not 'bytes'
`

**Comment by 41south** [comment] 2020-05-07 08:20
Yes sorry mine is also after the Weewx 4 and Python 3 upgrade

**Comment by poblabs** [comment] 2020-06-01 13:11
Are you still having this issue? I haven't seen it myself yet.

**Comment by 41south** [comment] 2020-06-01 20:25
Yep, every data cycle

Jun  2 08:20:24 raspberrypi weewx[10442] ERROR user.belchertown: Update
Checker: Error downloading GitHub Version data. The error is: HTTP Error
403: rate limit exceeded

Jun  2 08:20:24 raspberrypi weewx[10442] ERROR user.belchertown: Update
Checker: Error downloading GitHub Version data. The error is: HTTP Error
403: rate limit exceeded

Jun  2 08:20:25 raspberrypi weewx[10442] ERROR user.belchertown: Update
Checker: Error downloading GitHub Version data. The error is: HTTP Error
403: rate limit exceeded

Jun  2 08:20:25 raspberrypi weewx[10442] ERROR user.belchertown: Update
Checker: Error downloading GitHub Version data. The error is: HTTP Error
403: rate limit exceeded

Jun  2 08:20:26 raspberrypi weewx[10442] ERROR user.belchertown: Update
Checker: Error downloading GitHub Version data. The error is: HTTP Error
403: rate limit exceeded

Jun  2 08:20:26 raspberrypi weewx[10442] ERROR user.belchertown: Update
Checker: Error downloading GitHub Version data. The error is: HTTP Error
403: rate limit exceeded

Jun  2 08:20:27 raspberrypi weewx[10442] ERROR user.belchertown: Update
Checker: Error downloading GitHub Version data. The error is: HTTP Error
403: rate limit exceeded

Jun  2 08:20:27 raspberrypi weewx[10442] INFO weewx.cheetahgenerator:
Generated 11 files for report Belchertown in 6.87 seconds

**Comment by poblabs** [comment] 2020-06-01 20:28
So strange. In your skin.conf, change this option below and restart weewx. Does it still happen?

`    check_for_updates = 0`

**Comment by 41south** [comment] 2020-06-01 20:32
Just waiting for the next cycle but this error was also in the log

Jun  2 08:25:25 raspberrypi weewx[10442] ERROR user.belchertown: Update
Checker: Error downloading GitHub Version data. The error is: the JSON
object must be str, not 'bytes'

Jun  2 08:25:25 raspberrypi weewx[10442] ERROR user.belchertown: Update
Checker: Error downloading GitHub Version data. The error is: the JSON
object must be str, not 'bytes'

Jun  2 08:25:26 raspberrypi weewx[10442] ERROR user.belchertown: Update
Checker: Error downloading GitHub Version data. The error is: the JSON
object must be str, not 'bytes'

Jun  2 08:25:26 raspberrypi weewx[10442] ERROR user.belchertown: Update
Checker: Error downloading GitHub Version data. The error is: the JSON
object must be str, not 'bytes'

Jun  2 08:25:27 raspberrypi weewx[10442] ERROR user.belchertown: Update
Checker: Error downloading GitHub Version data. The error is: the JSON
object must be str, not 'bytes'

Jun  2 08:25:27 raspberrypi weewx[10442] ERROR user.belchertown: Update
Checker: Error downloading GitHub Version data. The error is: the JSON
object must be str, not 'bytes'

**Comment by poblabs** [comment] 2020-06-01 20:33
Ah that's helpful (even though I'm not seeing that). 

Remind me your setup? Python 3, weewx 4, Belchertown 1.1?

**Comment by 41south** [comment] 2020-06-01 20:42
That is correct and no errors with update set to '0'

**Comment by poblabs** [comment] 2020-06-01 20:47
I'll play around with it and see if i can re-create it or at least put in a patch to try and prevent it.

**Comment by kacnje** [comment] 2020-06-02 04:00
I can also confirm that the same error is still in the log. 
Latest Weewx version (from yesterday), Python 3, Belchertown (I do not know where to look, but it looks like the latest version from 9th April).

**Comment by poblabs** [comment] 2020-06-02 13:40
I think I have a fix ready to be tested, but the whole thing has me wondering about the effectiveness of the update checker if GitHub is going to rate limit people anyways. I could either host an update checker on my own site, or get rid of it.

**Comment by poblabs** [comment] 2020-06-02 16:45
So this commit fixes 1 of the 2 errors you've posted. Let me know if you want to give it a try - download the belchertown.py file, restart weewx and re-enable the check for updates.

Maybe this fix will make GitHub happy again and not rate limit you.

https://github.com/poblabs/weewx-belchertown/commit/3c877903b778392635ca7718ea5b0bf891873877

**Comment by 41south** [comment] 2020-06-02 20:21
Cool, give me a couple of hours and I'll pop it in and let you know 👍

**Comment by poblabs** [comment] 2020-06-02 20:23
No problem. You'll also want to run the development version of everything (if you haven't upgraded yet)

**Comment by 41south** [comment] 2020-06-02 20:27
Ah, no I haven't done that yet so will do that first. Will that also drop
Darksky?

**Comment by poblabs** [comment] 2020-06-02 20:29
Yes it will drop DarkSky. 

Instead of upgrading everything, grab this attached belchertown.py which is the 1.1 version and the same potential fix applied. Let me know if it works for you. 


[belchertown.zip](https://github.com/poblabs/weewx-belchertown/files/4719543/belchertown.zip)

**Comment by 41south** [comment] 2020-06-02 23:51
Still getting the update error, but I think a different one?

Jun  3 11:50:20 raspberrypi weewx[8720] ERROR user.belchertown: Update
Checker: Error downloading GitHub Version data. The error is:
'HTTPResponse' object has no attribute 'decode'

Jun  3 11:50:21 raspberrypi weewx[8720] ERROR user.belchertown: Update
Checker: Error downloading GitHub Version data. The error is:
'HTTPResponse' object has no attribute 'decode'

Jun  3 11:50:22 raspberrypi weewx[8720] ERROR user.belchertown: Update
Checker: Error downloading GitHub Version data. The error is:
'HTTPResponse' object has no attribute 'decode'

Jun  3 11:50:23 raspberrypi weewx[8720] ERROR user.belchertown: Update
Checker: Error downloading GitHub Version data. The error is:
'HTTPResponse' object has no attribute 'decode'

Jun  3 11:50:23 raspberrypi weewx[8720] ERROR user.belchertown: Update
Checker: Error downloading GitHub Version data. The error is: HTTP Error
403: rate limit exceeded

Jun  3 11:50:24 raspberrypi weewx[8720] ERROR user.belchertown: Update
Checker: Error downloading GitHub Version data. The error is: HTTP Error
403: rate limit exceeded

Jun  3 11:50:24 raspberrypi weewx[8720] ERROR user.belchertown: Update
Checker: Error downloading GitHub Version data. The error is: HTTP Error
403: rate limit exceeded

Jun  3 11:50:24 raspberrypi weewx[8720] ERROR user.belchertown: Update
Checker: Error downloading GitHub Version data. The error is: HTTP Error
403: rate limit exceeded

Jun  3 11:50:25 raspberrypi weewx[8720] ERROR user.belchertown: Update
Checker: Error downloading GitHub Version data. The error is: HTTP Error
403: rate limit exceeded

Jun  3 11:50:25 raspberrypi weewx[8720] ERROR user.belchertown: Update
Checker: Error downloading GitHub Version data. The error is: HTTP Error
403: rate limit exceeded

Jun  3 11:50:26 raspberrypi weewx[8720] ERROR user.belchertown: Update
Checker: Error downloading GitHub Version data. The error is: HTTP Error
403: rate limit exceeded

Jun  3 11:50:26 raspberrypi weewx[8720] INFO weewx.cheetahgenerator:
Generated 11 files for report Belchertown in 6.71 seconds

Jun  3 11:50:26 raspberrypi weewx[8720] INFO weewx.reportengine: Copied 2
files to /var/www/html/weewx/belchertown

**Comment by 41south** [comment] 2020-06-02 23:53
Oh and it went through about 4 cycles of the first error before hitting the
403 one, so I think that's just a side effect?

**Comment by poblabs** [comment] 2020-06-03 00:02
The 403 shouldn't happen. My guess is that the skin is failing and repeatedly asking for upgrade info and GitHub then 403's it to shut it up. Oops 😄 

Little more trial and error since I'm not experiencing this - try this version

[belchertown.zip](https://github.com/poblabs/weewx-belchertown/files/4720242/belchertown.zip)

**Comment by 41south** [comment] 2020-06-03 01:26
I agree on you thoughts with the 403 error

Jun  3 13:25:23 raspberrypi weewx[11672] ERROR user.belchertown: Update
Checker: Error downloading GitHub Version data. The error is: Expecting
value: line 1 column 1 (char 0)

**Comment by poblabs** [comment] 2020-06-03 16:17
Let's try this again?

[belchertown.zip](https://github.com/poblabs/weewx-belchertown/files/4724668/belchertown.zip)

**Comment by 41south** [comment] 2020-06-03 22:46
No dice sorry

Jun  4 10:45:25 raspberrypi weewx[9466] ERROR user.belchertown: Update
Checker: Error downloading GitHub Version data. The error is: 'str' object
has no attribute 'read'

**Comment by poblabs** [comment] 2020-06-03 22:47
This is a head scratcher. Let me spend more time with it. I know what's wrong, just can't find the right combination that works

**Comment by 41south** [comment] 2020-06-03 22:48
No rush at all, I've just turned off the check updates for now :)

**Comment by poblabs** [comment] 2020-06-11 12:37
I'm tempted to drop this feature. It's not working as intended. In regards to the 1.2 upgrade, I've added DarkSky back in in addition to Aeris, so it'll give some flexibility for those who aren't ready to switch yet

**Comment by poblabs** [comment] 2020-06-11 16:19
Alright, one last attempt. Give this a try? Restart weewx when done. 

[belchertown.zip](https://github.com/poblabs/weewx-belchertown/files/4766003/belchertown.zip)

**Comment by 41south** [comment] 2020-06-11 20:21
Righto, will let you know how it goes but I certainly have no issue with
dropping the feature 😊

**Comment by 41south** [comment] 2020-06-15 09:54
No go I'm afraid - now this error

Jun 15 21:45:25 raspberrypi weewx[26755] ERROR weewx.reportengine: Caught
unrecoverable exception in generator
'weewx.cheetahgenerator.CheetahGenerator'

Jun 15 21:45:25 raspberrypi weewx[26755] ERROR weewx.reportengine:
****  name 'html_root' is not defined

Jun 15 21:45:25 raspberrypi weewx[26755] ERROR weewx.reportengine:
****  Traceback (most recent call last):

Jun 15 21:45:25 raspberrypi weewx[26755] ERROR weewx.reportengine:
****    File "/usr/share/weewx/weewx/reportengine.py", line 197, in run

Jun 15 21:45:25 raspberrypi weewx[26755] ERROR weewx.reportengine:
****      obj.start()

Jun 15 21:45:25 raspberrypi weewx[26755] ERROR weewx.reportengine:
****    File "/usr/share/weewx/weewx/reportengine.py", line 280, in start

Jun 15 21:45:25 raspberrypi weewx[26755] ERROR weewx.reportengine:
****      self.run()

Jun 15 21:45:25 raspberrypi weewx[26755] ERROR weewx.reportengine:
****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 150, in run

Jun 15 21:45:25 raspberrypi weewx[26755] ERROR weewx.reportengine:
****      ngen = self.generate(gen_dict[section_name], self.gen_ts)

Jun 15 21:45:25 raspberrypi weewx[26755] ERROR weewx.reportengine:
****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in
generate

Jun 15 21:45:25 raspberrypi weewx[26755] ERROR weewx.reportengine:
****      ngen += self.generate(section[subsection], gen_ts)

Jun 15 21:45:25 raspberrypi weewx[26755] ERROR weewx.reportengine:
****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in
generate

Jun 15 21:45:25 raspberrypi weewx[26755] ERROR weewx.reportengine:
****      ngen += self.generate(section[subsection], gen_ts)

Jun 15 21:45:25 raspberrypi weewx[26755] ERROR weewx.reportengine:
****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 309, in
generate

Jun 15 21:45:25 raspberrypi weewx[26755] ERROR weewx.reportengine:
****      default_binding)

Jun 15 21:45:25 raspberrypi weewx[26755] ERROR weewx.reportengine:
****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 376, in
_getSearchList

Jun 15 21:45:25 raspberrypi weewx[26755] ERROR weewx.reportengine:
****      searchList += obj.get_extension_list(timespan, db_lookup)

Jun 15 21:45:25 raspberrypi weewx[26755] ERROR weewx.reportengine:
****    File "/usr/share/weewx/user/belchertown.py", line 738, in
get_extension_list

Jun 15 21:45:25 raspberrypi weewx[26755] ERROR weewx.reportengine:
****      github_version_file = html_root + "/json/github_version.json"

Jun 15 21:45:25 raspberrypi weewx[26755] ERROR weewx.reportengine:
****  NameError: name 'html_root' is not defined

Jun 15 21:45:25 raspberrypi weewx[26755] ERROR weewx.reportengine:
****  Generator terminated

**Comment by poblabs** [comment] 2020-06-15 13:05
This is an entirely new error, but I'm starting to think it's time to remove this option anyways. Not sure how useful it'll be and it'll be 1 less thing to keep troubleshooting 😄

**Comment by 41south** [comment] 2020-06-15 19:44
Haha, no arguments here Pat! I have it turned off again.

**Comment by poblabs** [comment] 2020-06-17 18:38
Removed in 1.2b6, closing

**Closed by poblabs** 2020-06-17 18:38 UTC
